// Phase 3 (Wave A) — chunk expansion batch 2, toward the ~250 target.
// [id, intention, en, hu, register, firstLesson, variants[], slots[]]
export const EXTRA_CHUNKS2 = [
  // permission & polite requests
  ["pm_canihave", "ask for something", "Can I have this, please?", "Megkaphatnám ezt, kérem?", "polite", "u05-l02", ["Could I have this?"], ["item"]],
  ["pm_mayisit", "ask to sit", "May I sit here?", "Leülhetek ide?", "polite", "u16-l01", ["Is this seat free?"], []],
  ["pm_canyoupass", "ask someone to pass", "Could you pass the salt, please?", "Ide tudná adni a sót, kérem?", "polite", "u16-l01", ["Pass the bread, please."], ["item"]],
  ["pm_doyoumind", "ask permission gently", "Do you mind if I open the window?", "Nem baj, ha kinyitom az ablakot?", "polite", "u10-l02", ["Is it okay if I open the window?"], []],
  // offering & helping
  ["of_canihelp", "offer help", "Can I help you?", "Segíthetek?", "polite", "u10-l01", ["Do you need help?"], []],
  ["of_wouldyoulike", "offer something", "Would you like some coffee?", "Kérsz egy kis kávét?", "warm", "u16-l01", ["Would you like a drink?"], ["item"]],
  ["of_letme", "offer to do it", "Let me help you.", "Hadd segítsek.", "warm", "u16-l01", ["I'll help you."], []],
  ["of_hereyouare", "give something", "Here you are.", "Tessék.", "neutral", "u05-l02", ["Here it is."], []],
  // apologising & thanking
  ["ap_soznumber", "apologise for a mistake", "Sorry, that's my mistake.", "Bocsánat, ez az én hibám.", "polite", "u11-l01", ["Sorry, my mistake."], []],
  ["ap_solate", "apologise for being late", "Sorry I'm late.", "Bocsánat a késésért.", "polite", "u06-l02", ["Sorry for being late."], []],
  ["th_kind", "thank warmly", "That's very kind of you.", "Nagyon kedves tőled.", "warm", "u16-l01", ["Thank you, that's so kind."], []],
  ["th_forhelp", "thank for help", "Thank you for your help.", "Köszönöm a segítségedet.", "warm", "u10-l01", ["Thanks for helping me."], []],
  // numbers, prices, dates
  ["nm_howmuchtotal", "ask the total", "How much is that altogether?", "Mennyi ez összesen?", "neutral", "u05-l02", ["What's the total?"], []],
  ["nm_itcosts", "state a price", "It costs ten euros.", "Tíz euróba kerül.", "neutral", "u05-l02", ["That's ten euros."], ["amount"]],
  ["nm_whatsdate", "ask the date", "What's the date today?", "Hányadika van ma?", "neutral", "u06-l01", ["What date is it?"], []],
  ["nm_myphone", "give a phone number", "My number is...", "A számom...", "neutral", "u07-l02", ["You can call me on..."], ["number"]],
  ["nm_whatsage", "ask about age", "How old are you?", "Hány éves vagy?", "neutral", "u02-l02", ["How old is she?"], []],
  // describing people & things
  ["ds_tall", "describe appearance", "She is tall and friendly.", "Magas és barátságos.", "neutral", "u03-l02", ["He is tall."], []],
  ["ds_looks", "say who someone resembles", "She looks like her mother.", "Az anyjára hasonlít.", "neutral", "u03-l02", ["He looks like his father."], []],
  ["ds_verynice", "describe a place", "It's a beautiful place.", "Gyönyörű hely.", "neutral", "u09-l01", ["It's a lovely town."], ["place"]],
  ["ds_bigger", "compare things", "This one is bigger than that one.", "Ez nagyobb, mint az.", "neutral", "u08-l02", ["Mine is smaller."], []],
  // health & pharmacy
  ["he_notwell", "say you feel unwell", "I don't feel well.", "Nem érzem jól magam.", "neutral", "u10-l02", ["I feel ill."], []],
  ["he_headache", "describe a symptom", "I have a headache.", "Fáj a fejem.", "neutral", "u10-l02", ["I have a cold."], ["symptom"]],
  ["he_medicine", "ask at a pharmacy", "Do you have something for a cold?", "Van valamije megfázásra?", "polite", "u10-l02", ["I need something for a headache."], []],
  ["he_doctor", "ask to see a doctor", "I need to see a doctor.", "Orvoshoz kell mennem.", "neutral", "u10-l02", ["Can I see a doctor?"], []],
  // agreeing / disagreeing / opinions
  ["ag_iagree", "agree", "Yes, I agree.", "Igen, egyetértek.", "neutral", "u08-l02", ["That's true."], []],
  ["ag_notreally", "disagree gently", "I'm not sure about that.", "Ebben nem vagyok biztos.", "polite", "u08-l02", ["I don't think so."], []],
  ["ag_inmyopinion", "give an opinion", "In my opinion, it's very good.", "Szerintem nagyon jó.", "neutral", "u08-l02", ["I think it's good."], ["opinion"]],
  ["ag_metoo", "share a feeling", "Me too!", "Én is!", "neutral", "u08-l01", ["So do I."], []],
  ["ag_reallythink", "ask an opinion", "What do you think?", "Te mit gondolsz?", "neutral", "u08-l02", ["Do you like it?"], []],
  // phone / video (extra)
  ["ph_whoscalling", "ask who is calling", "Who's calling, please?", "Ki keres, kérem?", "polite", "u07-l01", ["Who is it?"], []],
  ["ph_holdon", "ask to hold", "Hold on a moment, please.", "Egy pillanat türelmet kérek.", "polite", "u07-l01", ["Please hold on."], []],
  ["ph_callback", "offer to call back", "I'll call you back.", "Visszahívlak.", "neutral", "u07-l02", ["Can I call you back?"], []],
  ["ph_speakup", "ask to speak louder", "Could you speak up, please?", "Tudna hangosabban beszélni?", "polite", "u07-l01", ["I can't hear you well."], []],
  // teaching (extra)
  ["te_repeatafter", "ask to repeat after you", "Repeat after me, please.", "Ismételd utánam, kérlek.", "neutral", "u11-l01", ["Say it with me."], []],
  ["te_writedown", "give an instruction", "Please write it in your notebook.", "Írd le a füzetedbe, kérlek.", "neutral", "u11-l01", ["Write this down, please."], []],
  ["te_understand", "check understanding", "Do you understand?", "Érted?", "neutral", "u11-l01", ["Is that clear?"], []],
  ["te_seeyounext", "close a lesson warmly", "See you next week. Bye!", "Jövő héten találkozunk. Szia!", "warm", "u11-l02", ["See you next time!"], []],
  // past / stories (extra)
  ["pa_lastnight", "talk about last night", "Last night I watched a film.", "Tegnap este filmet néztem.", "neutral", "u12-l01", ["Yesterday I stayed home."], []],
  ["pa_itwasgreat", "give a past reaction", "It was really lovely.", "Nagyon kedves volt.", "neutral", "u12-l02", ["We had a great time."], []],
  ["pa_didyou", "ask a past question", "Did you have a good weekend?", "Jó hétvégéd volt?", "neutral", "u12-l02", ["Did you enjoy it?"], []],
  ["pa_wentto2", "narrate a trip", "We went to the lake and had a picnic.", "Elmentünk a tóhoz és piknikeztünk.", "neutral", "u12-l02", ["We visited the city."], []],
  // future / plans (extra)
  ["fu_planto", "state a plan", "Next week I'm going to visit my sister.", "Jövő héten meglátogatom a nővéremet.", "neutral", "u13-l01", ["I'm going to travel soon."], ["time"]],
  ["fu_wouldliketo", "express a wish", "I'd like to visit Denmark one day.", "Egy nap szeretnék Dániába menni.", "neutral", "u13-l01", ["I hope to travel more."], ["place"]],
  ["fu_needto2", "state a necessity", "I need to book a ticket.", "Jegyet kell foglalnom.", "neutral", "u13-l01", ["I have to pack."], []],
  ["fu_lookingforward", "express anticipation", "I'm looking forward to it.", "Nagyon várom.", "warm", "u13-l01", ["I can't wait."], [], ],
  // family events
  ["ev_comingover", "invite to your home", "Come to dinner on Sunday.", "Gyere vacsorára vasárnap.", "warm", "u16-l01", ["Join us for lunch."], ["day"]],
  ["ev_happybday", "wish a happy birthday", "Happy birthday!", "Boldog születésnapot!", "warm", "u16-l01", ["Many happy returns!"], []],
  ["ev_merryxmas", "seasonal greeting", "Merry Christmas!", "Boldog karácsonyt!", "warm", "u16-l01", ["Happy Christmas!"], []],
  ["ev_cheers", "make a toast", "Cheers! To the family!", "Egészségedre! A családra!", "warm", "u16-l01", ["Here's to us!"], []],
  ["ev_thanksforcoming", "thank guests", "Thank you all for coming.", "Köszönöm, hogy eljöttetek.", "warm", "u16-l01", ["So glad you came."], []],
  // town / directions (extra)
  ["tw_excusewhere", "ask for a place politely", "Excuse me, where is the station?", "Elnézést, hol van az állomás?", "polite", "u09-l01", ["Excuse me, where's the market?"], ["place"]],
  ["tw_straighton", "understand a direction", "Go straight on and turn left.", "Menj egyenesen, majd fordulj balra.", "neutral", "u09-l01", ["Turn right at the corner."], []],
  ["tw_howfar", "ask distance & time", "How long does it take?", "Mennyi ideig tart?", "neutral", "u09-l01", ["Is it far to walk?"], []],
  ["tw_overthere", "point something out", "It's over there, on the right.", "Ott van, jobbra.", "neutral", "u09-l01", ["It's just around the corner."], []],
  // airport / travel (extra)
  ["ai_luggage", "talk about luggage", "I have one suitcase and a bag.", "Egy bőröndöm és egy táskám van.", "neutral", "u14-l01", ["Just hand luggage."], []],
  ["ai_delayed", "understand a delay", "Is the flight delayed?", "Késik a járat?", "neutral", "u14-l02", ["Is my flight on time?"], []],
  ["ai_whichgate", "confirm the gate", "Which gate is it, please?", "Melyik kapu az, kérem?", "polite", "u14-l01", ["Where do I board?"], []],
  ["ai_help_bags", "ask for help with bags", "Could you help me with my bags?", "Tudna segíteni a csomagjaimmal?", "polite", "u14-l01", ["Can you help me carry this?"], []],
  // restaurant / hotel (extra)
  ["rs_readyorder", "say you're ready to order", "We're ready to order.", "Készen állunk a rendelésre.", "neutral", "u10-l01", ["Can we order, please?"], []],
  ["rs_anythingelse", "respond to an offer", "No, that's all, thank you.", "Nem, ez minden, köszönöm.", "polite", "u10-l01", ["That's everything, thanks."], []],
  ["rs_cardorcash", "answer payment question", "Can I pay by card?", "Fizethetek kártyával?", "neutral", "u10-l01", ["I'll pay in cash."], []],
  ["rs_lovelymeal", "compliment the meal", "That was a lovely meal.", "Ez finom étkezés volt.", "warm", "u10-l01", ["The food was delicious."], []],
  // weather / small talk (extra)
  ["we_forecast", "ask about the weather", "What's the weather like today?", "Milyen ma az idő?", "neutral", "u06-l02", ["Is it going to rain?"], []],
  ["we_takecoat", "give practical advice", "Take a coat, it's cold.", "Vigyél kabátot, hideg van.", "neutral", "u06-l02", ["Bring an umbrella."], []],
  // survival / repair (extra)
  ["rp_howspell", "ask for spelling", "How do you spell that?", "Hogy írják ezt?", "neutral", "u09-l01", ["Can you spell it?"], []],
  ["rp_whatmeans", "ask a word's meaning", "What does this word mean?", "Mit jelent ez a szó?", "neutral", "u07-l02", ["What does that mean?"], ["word"]],
  ["rp_slowlyplease", "ask to slow down", "More slowly, please.", "Lassabban, kérem.", "polite", "u07-l01", ["Not so fast, please."], []],
  ["rp_almostget", "buy thinking time", "Let me think for a moment.", "Hadd gondolkodjam egy percet.", "neutral", "u08-l02", ["Give me a second."], []],

  // ---- batch 2b: reach the target ----
  ["sm_longtime2", "greet after a long time", "It's been a long time!", "Rég találkoztunk!", "warm", "u01-l02", ["Long time no see!"], []],
  ["sm_howwasday", "ask about someone's day", "How was your day?", "Milyen napod volt?", "neutral", "u04-l01", ["How is your day going?"], []],
  ["id_pleased", "polite first meeting", "Pleased to meet you.", "Örvendek.", "polite", "u01-l02", ["Nice to meet you."], []],
  ["id_thisismy", "introduce a partner", "This is my partner, Ákos.", "Ez a párom, Ákos.", "neutral", "u02-l02", ["Let me introduce Ákos."], ["name"]],
  ["fam_youngest", "describe family position", "I'm the oldest in the family.", "Én vagyok a legidősebb a családban.", "neutral", "u02-l01", ["She's the youngest."], []],
  ["op_dependson", "give a nuanced answer", "It depends.", "Attól függ.", "neutral", "u08-l02", ["That depends."], []],
  ["fe_worried", "share a worry", "I'm a little worried.", "Kicsit aggódom.", "neutral", "u15-l01", ["I'm worried about the flight."], []],
  ["fe_excited", "share excitement", "I'm really excited!", "Nagyon izgatott vagyok!", "warm", "u13-l01", ["I can't wait!"], []],
  ["dl_freetime", "talk about free time", "In my free time I like reading.", "A szabadidőmben szeretek olvasni.", "neutral", "u08-l01", ["I read in my free time."], ["activity"]],
  ["dl_busytoday", "say you are busy", "I'm quite busy today.", "Ma elég elfoglalt vagyok.", "neutral", "u06-l02", ["I have a lot to do."], []],
  ["fd_allergic", "state a food limit", "I don't eat meat.", "Nem eszem húst.", "neutral", "u05-l01", ["I'm vegetarian."], []],
  ["fd_favourite", "name a favourite food", "My favourite food is soup.", "A kedvenc ételem a leves.", "neutral", "u05-l01", ["I love soup."], ["food"]],
  ["tm_seeyouat", "arrange a meeting time", "See you at three o'clock.", "Háromkor találkozunk.", "neutral", "u06-l01", ["Let's meet at three."], ["time"]],
  ["we_lovely2", "comment warmly on weather", "What a lovely day!", "Micsoda gyönyörű nap!", "warm", "u06-l02", ["Beautiful weather today!"], []],
  ["pl_freetomorrow", "check availability", "Are you free tomorrow?", "Ráérsz holnap?", "neutral", "u06-l02", ["Do you have time tomorrow?"], []],
  ["ph_gooutside", "explain a delay on a call", "One moment, the signal is weak.", "Egy pillanat, gyenge a jel.", "neutral", "u07-l01", ["The signal is bad here."], []],
  ["tw_isitclose", "ask if somewhere is near", "Is it near here?", "Közel van ide?", "neutral", "u09-l01", ["Is the station close?"], []],
  ["tr_lastbus", "ask about the last bus", "When is the last bus?", "Mikor megy az utolsó busz?", "neutral", "u09-l02", ["What time is the last train?"], []],
  ["ai_iamnervous", "tell staff you're anxious", "I'm a nervous traveller.", "Ideges utas vagyok.", "neutral", "u14-l01", ["I get nervous at airports."], []],
  ["fl_thankyou", "thank the crew", "Thank you, that's very kind.", "Köszönöm, nagyon kedves.", "warm", "u15-l01", ["Thank you so much."], []],
  ["rs_couldwehave", "make a table request", "Could we have the menu, please?", "Kaphatnánk egy étlapot, kérem?", "polite", "u10-l01", ["Can we see the menu?"], []],
  ["sv_wheretoilet2", "ask for facilities", "Where are the toilets, please?", "Hol vannak a mosdók, kérem?", "polite", "u10-l01", ["Excuse me, where's the bathroom?"], []],
  ["te_greatjob", "praise a student warmly", "Great job today!", "Nagyszerű munka ma!", "warm", "u11-l01", ["You did really well!"], []],
  ["te_onemore", "ask for one more try", "One more time, please.", "Még egyszer, kérlek.", "neutral", "u11-l01", ["Let's do it again."], []],
  ["pa_bornin", "say where you're from originally", "I was born in Hungary.", "Magyarországon születtem.", "neutral", "u12-l01", ["I grew up in Hungary."], ["place"]],
  ["fu_hopetosee", "express hope to meet", "I hope to see you soon.", "Remélem, hamarosan látlak.", "warm", "u16-l01", ["I hope we meet again soon."], []],
  ["ev_soproud", "express pride at an event", "I'm so proud of you.", "Nagyon büszke vagyok rád.", "warm", "u16-l01", ["We're all proud of you."], []],
  ["ev_comein", "welcome guests in", "Come in, make yourself at home.", "Gyere be, érezd otthon magad.", "warm", "u16-l01", ["Please, come in."], []],
  ["rp_didyousay", "confirm what was said", "Did you say Saturday?", "Szombatot mondtál?", "neutral", "u06-l02", ["Sorry, did you say Monday?"], ["day"]],
  ["rp_letmecheck", "buy time to check", "Let me check.", "Hadd nézzem meg.", "neutral", "u13-l02", ["Just a second, let me look."], []],
  ["op_soundsgood", "react positively to a plan", "That sounds great!", "Ez remekül hangzik!", "warm", "u06-l02", ["Sounds lovely!"], []],
  ["op_whatapity", "react with sympathy", "Oh, what a pity!", "Ó, milyen kár!", "neutral", "u12-l02", ["That's a shame."], []],
  ["he_getwell", "wish someone well", "Get well soon!", "Jobbulást!", "warm", "u10-l02", ["I hope you feel better."], []],
  ["fd_cheers2", "toast at the table", "Enjoy your meal!", "Jó étvágyat!", "warm", "u16-l01", ["Bon appétit!"], []],
  ["sm_goodnight", "say good night warmly", "Good night, sleep well.", "Jó éjt, aludj jól.", "warm", "u04-l01", ["Sleep well!"], []],
  ["id_wherework", "ask where someone works", "Where do you work?", "Hol dolgozol?", "neutral", "u03-l02", ["What company do you work for?"], []],
  ["tw_canyoushow", "ask to be shown on a map", "Could you show me on the map?", "Meg tudná mutatni a térképen?", "polite", "u09-l01", ["Show me where it is, please."], []],
  ["ai_isthisright", "confirm you're in the right place", "Is this the right way to the gate?", "Erre van a kapu?", "neutral", "u14-l01", ["Am I going the right way?"], []],
  ["fl_couldyourepeat", "ask crew to repeat", "Sorry, could you repeat that?", "Elnézést, meg tudná ismételni?", "polite", "u15-l01", ["Pardon, again please?"], []],
  ["ev_wishyou", "offer good wishes", "I wish you all the best.", "Minden jót kívánok.", "warm", "u16-l01", ["All the best to you."], []],
];
