// Curated example sentences (v1.9.1) — anchored to Marta's life, replacing bland
// grammar-safe templates. Generated from the 6-writer curation pass; HU flagged for review.
// Merged over EXAMPLES in build-data.mjs (these win on key conflicts).
export const EXAMPLES_EXTRA = {
  "address": ["What is your address?","Mi a címed?"],
  "after": ["I rest after my lesson.","Az órám után pihenek."],
  "again": ["Say it again, please.","Mondd újra, kérlek."],
  "age": ["We are the same age.","Egyidősek vagyunk."],
  "ago": ["I called her an hour ago.","Egy órája hívtam fel."],
  "agree": ["I agree with you.","Egyetértek veled."],
  "almost": ["I am almost ready.","Majdnem kész vagyok."],
  "angry": ["He is angry with me.","Mérges rám."],
  "animal": ["A cow is a big animal.","A tehén egy nagy állat."],
  "answer": ["Please answer the question.","Kérlek, válaszolj a kérdésre."],
  "app": ["I use a new app.","Egy új appot használok."],
  "apple": ["The apple is fresh and sweet.","Az alma friss és édes."],
  "april": ["It rains a lot in April.","Áprilisban sokat esik."],
  "arm": ["I hold the bag in my arm.","A karomban tartom a táskát."],
  "arrive": ["We arrive in Prague tonight.","Ma este megérkezünk Prágába."],
  "artist": ["Esztella is an artist.","Esztella művész."],
  "august": ["It is very warm in August.","Augusztusban nagyon meleg van."],
  "back": ["My seat is at the back.","A helyem hátul van."],
  "bad": ["The weather is bad today.","Ma rossz az idő."],
  "bag": ["My bag is very heavy.","A táskám nagyon nehéz."],
  "banana": ["The banana is yellow and sweet.","A banán sárga és édes."],
  "bank": ["The bank is near the square.","A bank a tér közelében van."],
  "basket": ["My basket is full of fruit.","A kosaram tele van gyümölccsel."],
  "bathroom": ["The towel is in the bathroom.","A törölköző a fürdőszobában van."],
  "beach": ["We walk on the beach.","Sétálunk a strandon."],
  "bed": ["My bed is very soft.","Az ágyam nagyon puha."],
  "bedroom": ["My bedroom is warm and quiet.","A hálószobám meleg és csendes."],
  "before": ["I have coffee before my lesson.","Az órám előtt kávézom."],
  "begin": ["We begin at nine o'clock.","Kilenc órakor kezdünk."],
  "belgium": ["Rita works in Belgium.","Rita Belgiumban dolgozik."],
  "bench": ["We sit on the bench.","A padon ülünk."],
  "best": ["This is the best day.","Ez a legjobb nap."],
  "better": ["I feel better today.","Ma jobban vagyok."],
  "bicycle": ["Panna has a new bicycle.","Pannának új biciklije van."],
  "big": ["Kira has a big house.","Kirának nagy háza van."],
  "bird": ["A small bird sings outside.","Egy kis madár énekel kint."],
  "birthday": ["Today is Panna's birthday.","Ma van Panna születésnapja."],
  "biscuit": ["I eat a biscuit with coffee.","Kekszet eszem a kávéhoz."],
  "black": ["My coffee is black.","A kávém fekete."],
  "blue": ["The sky is blue today.","Ma kék az ég."],
  "boarding": ["Boarding starts in an hour.","A beszállás egy óra múlva kezdődik."],
  "boat": ["We take a boat on Balaton.","Hajózunk a Balatonon."],
  "body": ["I move my body every day.","Minden nap mozgatom a testem."],
  "boring": ["This film is quite boring.","Ez a film elég unalmas."],
  "borrow": ["Can I borrow your pen?","Kölcsönkérhetem a tolladat?"],
  "bottle": ["The bottle of water is cold.","A vizesüveg hideg."],
  "box": ["The photos are in a box.","A fényképek egy dobozban vannak."],
  "boy": ["The boy asks a question.","A fiú feltesz egy kérdést."],
  "break": ["Please don't break the mirror.","Kérlek, ne törd el a tükröt."],
  "bridge": ["The bridge is in Budapest.","A híd Budapesten van."],
  "bright": ["The sun is very bright.","A nap nagyon fényes."],
  "bring": ["Please bring your map.","Kérlek, hozd a térképet."],
  "brown": ["The leaves are brown now.","A levelek most barnák."],
  "build": ["David and Marlene build a house.","David és Marlene házat építenek."],
  "building": ["That building is very old.","Az az épület nagyon régi."],
  "busy": ["I am very busy today.","Ma nagyon elfoglalt vagyok."],
  "cafe": ["We meet at the cafe.","A kávézóban találkozunk."],
  "card": ["I pay with my card.","A kártyámmal fizetek."],
  "carrot": ["Luna eats a fresh carrot.","Luna egy friss répát eszik."],
  "carry": ["I carry the heavy bag.","Viszem a nehéz táskát."],
  "cat": ["My cat sleeps on the sofa.","A macskám a kanapén alszik."],
  "catch": ["I must catch the train.","El kell érnem a vonatot."],
  "centre": ["We live in the centre.","A központban lakunk."],
  "chair": ["Please sit on this chair.","Kérlek, ülj erre a székre."],
  "change": ["We change trains in Prague.","Prágában átszállunk."],
  "cheap": ["The vegetables are cheap today.","A zöldség ma olcsó."],
  "check-in": ["We go to the check-in.","A check-inhez megyünk."],
  "chicken": ["We eat chicken at the restaurant.","Csirkét eszünk az étteremben."],
  "choose": ["I choose a nice dessert.","Választok egy finom desszertet."],
  "church": ["The church is very old.","A templom nagyon régi."],
  "cinema": ["We go to the cinema.","Moziba megyünk."],
  "classroom": ["The classroom is very quiet.","Az osztályterem nagyon csendes."],
  "clean": ["I clean the kitchen now.","Most kitakarítom a konyhát."],
  "click": ["Click on the blue button.","Kattints a kék gombra."],
  "climb": ["The children climb the hill.","A gyerekek felmásznak a dombra."],
  "clock": ["The clock is on the wall.","Az óra a falon van."],
  "close": ["Please close the door.","Kérlek, csukd be az ajtót."],
  "closed": ["The shop is closed today.","A bolt ma zárva van."],
  "cloud": ["A white cloud is above us.","Egy fehér felhő van felettünk."],
  "cloudy": ["The sky is grey and cloudy.","Az ég szürke és felhős."],
  "coat": ["I wear a warm coat.","Meleg kabátot veszek fel."],
  "cold": ["The water is very cold.","A víz nagyon hideg."],
  "colour": ["Blue is my favourite colour.","A kék a kedvenc színem."],
  "comfortable": ["The chair is comfortable.","A szék kényelmes."],
  "cool": ["The evening is nice and cool.","Az este kellemes és hűvös."],
  "corner": ["The shop is on the corner.","A bolt a sarkon van."],
  "cost": ["How much does it cost?","Mennyibe kerül?"],
  "cousin": ["My cousin lives in Denmark.","Az unokatestvérem Dániában él."],
  "cow": ["The cow eats green grass.","A tehén zöld füvet eszik."],
  "cup": ["I drink a cup of tea.","Iszom egy csésze teát."],
  "cut": ["I cut the bread for you.","Felvágom neked a kenyeret."],
  "dance": ["Margó and I dance together.","Margóval együtt táncolunk."],
  "dark": ["The room is very dark.","A szoba nagyon sötét."],
  "date": ["What is the date today?","Milyen dátum van ma?"],
  "day": ["It is a sunny day.","Napos nap van."],
  "december": ["We meet the family in December.","Decemberben találkozunk a családdal."],
  "decide": ["I can't decide yet.","Még nem tudok dönteni."],
  "deep": ["The lake is very deep.","A tó nagyon mély."],
  "delicious": ["Aunt Eva's dinner is delicious.","Éva néni vacsorája finom."],
  "denmark": ["Kira lives in Denmark.","Kira Dániában él."],
  "desk": ["The desk is over there.","A pult ott van."],
  "dessert": ["The dessert is on the table.","A desszert az asztalon van."],
  "different": ["Prague is very different.","Prága nagyon más."],
  "difficult": ["English is a bit difficult.","Az angol egy kicsit nehéz."],
  "dirty": ["The dog is very dirty.","A kutya nagyon piszkos."],
  "doctor": ["I see the doctor tomorrow.","Holnap megyek az orvoshoz."],
  "dog": ["The dog runs in the garden.","A kutya fut a kertben."],
  "draw": ["Panna likes to draw horses.","Panna szeret lovakat rajzolni."],
  "dress": ["Kira wears a pretty dress.","Kira egy szép ruhát visel."],
  "drive": ["David can drive a car.","David tud autót vezetni."],
  "driver": ["David is a bus driver.","David buszsofőr."],
  "drop": ["I drop my keys sometimes.","Néha leejtem a kulcsomat."],
  "dry": ["The towel is now dry.","A törölköző most száraz."],
  "duck": ["A duck swims on the lake.","Egy kacsa úszik a tavon."],
  "ear": ["I have a warm hat on my ear.","Meleg sapka van a fülemen."],
  "early": ["I wake up early.","Korán ébredek."],
  "east": ["The sun rises in the east.","A nap keleten kel fel."],
  "easy": ["This lesson is very easy.","Ez a lecke nagyon könnyű."],
  "egg": ["I eat an egg for breakfast.","Eszem egy tojást reggelire."],
  "eight": ["We start at eight o'clock.","Nyolc órakor kezdünk."],
  "eighteen": ["Emma is eighteen next year.","Emma jövőre tizennyolc éves."],
  "eighty": ["Aunt Eva is eighty now.","Éva néni most nyolcvan éves."],
  "eleven": ["Panna is eleven years old.","Panna tizenegy éves."],
  "email": ["I send David an email.","Küldök Davidnek egy e-mailt."],
  "engineer": ["Endika is an engineer.","Endika mérnök."],
  "england": ["We fly to England tomorrow.","Holnap Angliába repülünk."],
  "enter": ["We enter the museum.","Belépünk a múzeumba."],
  "euro": ["The coffee costs one euro.","A kávé egy euróba kerül."],
  "every": ["I call Kira every weekend.","Minden hétvégén hívom Kirát."],
  "excited": ["I am excited about Denmark.","Izgatott vagyok Dánia miatt."],
  "expensive": ["The restaurant is very expensive.","Az étterem nagyon drága."],
  "eye": ["My eye is a little tired.","Kicsit fáradt a szemem."],
  "face": ["I wash my face in the morning.","Reggel megmosom az arcom."],
  "fall": ["The leaves fall in autumn.","A levelek ősszel hullanak."],
  "famous": ["He is a famous artist.","Ő híres művész."],
  "far": ["The airport is quite far.","A repülőtér elég messze van."],
  "fast": ["The train is very fast.","A vonat nagyon gyors."],
  "february": ["My lessons start in February.","Az óráim februárban kezdődnek."],
  "feed": ["I feed the birds in the garden.","Megetetem a madarakat a kertben."],
  "feel": ["I feel very happy today.","Ma nagyon boldognak érzem magam."],
  "field": ["The horse runs in the field.","A ló fut a mezőn."],
  "fifteen": ["We wait fifteen minutes.","Tizenöt percet várunk."],
  "fifty": ["The book has fifty pages.","A könyvnek ötven oldala van."],
  "fill": ["I fill the glass with water.","Megtöltöm a poharat vízzel."],
  "film": ["We watched a good film.","Néztünk egy jó filmet."],
  "find": ["I can't find my bag.","Nem találom a táskámat."],
  "finish": ["We finish the lesson early.","Korán befejezzük az órát."],
  "first": ["This is my first visit.","Ez az első látogatásom."],
  "five": ["The lesson starts at five.","Az óra ötkor kezdődik."],
  "fix": ["Endre can fix my laptop.","Endre meg tudja javítani a laptopomat."],
  "flat": ["My flat is in Budapest.","A lakásom Budapesten van."],
  "floor": ["The dog sleeps on the floor.","A kutya a padlón alszik."],
  "flower": ["This flower is very pretty.","Ez a virág nagyon szép."],
  "fly": ["We fly to Denmark tomorrow.","Holnap Dániába repülünk."],
  "follow": ["Follow me to the taxi.","Kövess a taxihoz."],
  "foot": ["My foot is cold in winter.","Télen hideg a lábfejem."],
  "fork": ["I hold the fork in my hand.","A villát a kezemben tartom."],
  "forty": ["I have forty photos.","Negyven fényképem van."],
  "four": ["I have four online students.","Négy online diákom van."],
  "fourteen": ["Ákos is fourteen years old.","Ákos tizennégy éves."],
  "fresh": ["The bread is fresh today.","A kenyér ma friss."],
  "friday": ["I rest on Friday evening.","Péntek este pihenek."],
  "fridge": ["The milk is in the fridge.","A tej a hűtőben van."],
  "friendly": ["My students are very friendly.","A tanítványaim nagyon barátságosak."],
  "front": ["My seat is at the front.","A helyem elöl van."],
  "game": ["The children play a game.","A gyerekek játszanak egy játékot."],
  "germany": ["We drive through Germany.","Németországon át vezetünk."],
  "get": ["I get a letter today.","Ma kapok egy levelet."],
  "girl": ["The girl reads very well.","A kislány nagyon jól olvas."],
  "glass": ["I drink a glass of milk.","Iszom egy pohár tejet."],
  "good": ["You are a good student.","Jó tanuló vagy."],
  "grandparents": ["The children visit their grandparents.","A gyerekek meglátogatják a nagyszüleiket."],
  "great": ["We had a great day.","Nagyszerű napunk volt."],
  "green": ["The grass is green.","A fű zöld."],
  "grey": ["The sky is grey today.","Ma szürke az ég."],
  "ground": ["The bag is on the ground.","A táska a földön van."],
  "group": ["I teach a small group.","Kis csoportot tanítok."],
  "grow": ["I grow flowers in the garden.","Virágokat növesztek a kertben."],
  "guide": ["The guide speaks English.","Az idegenvezető beszél angolul."],
  "half": ["I drink half a cup.","Megiszom egy fél csészével."],
  "hand": ["I wash my hands before lunch.","Ebéd előtt kezet mosok."],
  "hard": ["The test was very hard.","A teszt nagyon nehéz volt."],
  "hat": ["Panna wears a red hat.","Panna piros kalapot visel."],
  "hate": ["I hate flying.","Utálok repülni."],
  "head": ["My head is tired tonight.","Ma este fáradt a fejem."],
  "heavy": ["The bag is too heavy.","A táska túl nehéz."],
  "high": ["The building is very high.","Az épület nagyon magas."],
  "hill": ["Our house is on a hill.","A házunk egy dombon van."],
  "hold": ["I hold the warm cup.","Fogom a meleg csészét."],
  "holiday": ["We go on holiday to Spain.","Nyaralni megyünk Spanyolországba."],
  "honey": ["I like honey in my tea.","Szeretem a mézet a teámban."],
  "hope": ["I hope to see you.","Remélem, látlak."],
  "horse": ["Panna loves her horse Luna.","Panna imádja a lovát, Lunát."],
  "hospital": ["Margó is in the hospital.","Margó a kórházban van."],
  "hot": ["The tea is too hot.","A tea túl forró."],
  "hour": ["I teach for one hour.","Egy órát tanítok."],
  "hundred": ["I know a hundred words.","Száz szót tudok."],
  "hungry": ["I am very hungry now.","Nagyon éhes vagyok most."],
  "hurt": ["My feet hurt after walking.","Fáj a lábam a séta után."],
  "idea": ["That is a good idea.","Ez jó ötlet."],
  "ill": ["My sister is ill today.","A nővérem ma beteg."],
  "important": ["Family is very important.","A család nagyon fontos."],
  "inside": ["It is warm inside today.","Ma bent meleg van."],
  "interesting": ["The book is very interesting.","A könyv nagyon érdekes."],
  "internet": ["The internet is very slow.","Az internet nagyon lassú."],
  "invite": ["I invite Rita to dinner.","Meghívom Ritát vacsorára."],
  "jacket": ["My jacket is on the chair.","A dzsekim a széken van."],
  "january": ["It is cold in January.","Januárban hideg van."],
  "job": ["Teaching is a lovely job.","A tanítás gyönyörű munka."],
  "journey": ["The journey is very long.","Az utazás nagyon hosszú."],
  "july": ["I visit Kira in July.","Júliusban meglátogatom Kirát."],
  "jump": ["The dog can jump high.","A kutya magasra tud ugrani."],
  "june": ["The days are long in June.","A napok hosszúak júniusban."],
  "keep": ["I keep my books here.","Itt tartom a könyveimet."],
  "key": ["I press the enter key.","Megnyomom az enter billentyűt."],
  "knife": ["The knife is very sharp.","A kés nagyon éles."],
  "knock": ["Please knock on the door.","Kérlek, kopogj az ajtón."],
  "lake": ["We swim in the lake.","Úszunk a tóban."],
  "lamp": ["Please turn on the lamp.","Kérlek, kapcsold fel a lámpát."],
  "late": ["The plane is very late.","A repülő nagyon késik."],
  "laugh": ["We laugh a lot together.","Sokat nevetünk együtt."],
  "leave": ["We leave at six.","Hatkor indulunk."],
  "leg": ["My leg is tired after the walk.","A séta után fáradt a lábam."],
  "lemon": ["I put a lemon in my tea.","Teszek egy citromot a teámba."],
  "let": ["Let me help you.","Hadd segítsek."],
  "letter": ["I write a letter to Kira.","Írok egy levelet Kirának."],
  "library": ["Emma loves the library.","Emma szereti a könyvtárat."],
  "light": ["The kitchen is nice and light.","A konyha szép világos."],
  "list": ["I write a shopping list.","Írok egy bevásárlólistát."],
  "listen": ["I listen to my students.","Hallgatom a tanítványaimat."],
  "long": ["The flight is very long.","A repülőút nagyon hosszú."],
  "look": ["I look at the garden.","A kertet nézem."],
  "look for": ["I look for my seat.","Keresem a helyemet."],
  "lose": ["Don't lose your passport.","Ne veszítsd el az útleveled."],
  "loud": ["The music is too loud.","A zene túl hangos."],
  "lovely": ["The garden looks lovely.","A kert gyönyörűen néz ki."],
  "low": ["The bench is very low.","A pad nagyon alacsony."],
  "lucky": ["I am very lucky.","Nagyon szerencsés vagyok."],
  "manager": ["Marlene is a manager.","Marlene menedzser."],
  "map": ["I look at the map.","Nézem a térképet."],
  "march": ["The garden grows in March.","A kert márciusban nő."],
  "market": ["I buy fruit at the market.","A piacon veszek gyümölcsöt."],
  "may": ["The flowers open in May.","A virágok májusban nyílnak."],
  "meal": ["We have a big meal together.","Együtt eszünk egy nagy ételt."],
  "medicine": ["I take my medicine every day.","Minden nap beveszem a gyógyszeremet."],
  "middle": ["The park is in the middle.","A park középen van."],
  "minute": ["Please wait a minute.","Kérlek, várj egy percet."],
  "mirror": ["I look in the mirror.","Belenézek a tükörbe."],
  "miss": ["We miss the bus.","Lekéssük a buszt."],
  "mobile": ["I call Rita on my mobile.","Felhívom Ritát a mobilomon."],
  "modern": ["The kitchen is very modern.","A konyha nagyon modern."],
  "moment": ["Just a moment, please.","Csak egy pillanat, kérlek."],
  "monday": ["I teach on Monday morning.","Hétfő reggel tanítok."],
  "month": ["July is a warm month.","A július meleg hónap."],
  "moon": ["The moon is bright tonight.","A hold fényes ma este."],
  "mountain": ["The mountain is very high.","A hegy nagyon magas."],
  "mouth": ["I open my mouth wide.","Szélesre nyitom a szám."],
  "move": ["I move the chair now.","Most odébb teszem a széket."],
  "museum": ["The museum is in Budapest.","A múzeum Budapesten van."],
  "near": ["The bank is very near.","A bank nagyon közel van."],
  "new": ["I have a new student.","Van egy új tanítványom."],
  "nice": ["He is a nice man.","Ő kedves ember."],
  "night": ["I sleep well at night.","Éjszaka jól alszom."],
  "nine": ["The class finishes at nine.","Az óra kilenckor ér véget."],
  "nineteen": ["He is nineteen years old.","Ő tizenkilenc éves."],
  "ninety": ["The book has ninety pages.","A könyvnek kilencven oldala van."],
  "north": ["Denmark is in the north.","Dánia északon van."],
  "nose": ["My nose is cold outside.","Kint hideg az orrom."],
  "november": ["It is grey in November.","Novemberben szürke az idő."],
  "now": ["I teach my class now.","Most tanítom az órámat."],
  "number": ["What is your phone number?","Mi a telefonszámod?"],
  "nurse": ["The nurse is very kind.","A nővér nagyon kedves."],
  "october": ["The leaves are brown in October.","A levelek barnák októberben."],
  "office": ["David works in an office.","David egy irodában dolgozik."],
  "okay": ["Are you okay?","Jól vagy?"],
  "onion": ["I cut an onion for dinner.","Felvágok egy hagymát vacsorára."],
  "open": ["I open the window now.","Most kinyitom az ablakot."],
  "orange": ["I want an orange, please.","Kérek egy narancsot."],
  "order": ["I order tea in the café.","Teát rendelek a kávézóban."],
  "other": ["The other book is here.","A másik könyv itt van."],
  "outside": ["The children are playing outside.","A gyerekek kint játszanak."],
  "page": ["Open the next page, please.","Nyisd ki a következő oldalt, kérlek."],
  "pain": ["I have a pain in my back.","Fáj a hátam."],
  "paint": ["Emma wants to paint flowers.","Emma virágokat akar festeni."],
  "pan": ["I cook eggs in the pan.","Tojást sütök a serpenyőben."],
  "paper": ["I need some paper.","Szükségem van egy kis papírra."],
  "parents": ["Her parents live in Prague.","A szülei Prágában élnek."],
  "park": ["We walk in the park.","Sétálunk a parkban."],
  "party": ["We have a birthday party.","Van egy szülinapi bulink."],
  "pay": ["I pay for the coffee now.","Most fizetek a kávéért."],
  "pen": ["I write with a pen.","Tollal írok."],
  "pencil": ["The boy has a pencil.","A fiúnak van egy ceruzája."],
  "perfect": ["The weather is perfect today.","Ma tökéletes az idő."],
  "person": ["She is a kind person.","Ő egy kedves ember."],
  "pharmacy": ["The pharmacy is near the bank.","A gyógyszertár a bank közelében van."],
  "photo": ["I have a family photo.","Van egy családi fotóm."],
  "picture": ["Emma draws a nice picture.","Emma egy szép képet rajzol."],
  "pink": ["The roses are pink.","A rózsák rózsaszínűek."],
  "place": ["This is a nice place.","Ez egy szép hely."],
  "plate": ["Your plate is on the table.","A tányérod az asztalon van."],
  "platform": ["The train leaves from platform two.","A vonat a kettes vágányról indul."],
  "play": ["Panna and Emma play outside.","Panna és Emma kint játszanak."],
  "pot": ["The soup is in the pot.","A leves a fazékban van."],
  "potato": ["The potato is on my plate.","A krumpli a tányéromon van."],
  "practise": ["We practise English every day.","Minden nap gyakoroljuk az angolt."],
  "prefer": ["I prefer tea to coffee.","Jobban szeretem a teát, mint a kávét."],
  "present": ["I have a present for Kira.","Van egy ajándékom Kirának."],
  "pretty": ["The flowers are very pretty.","A virágok nagyon szépek."],
  "price": ["The price is on the apple.","Az ár az almán van."],
  "problem": ["There is a small problem.","Van egy kis probléma."],
  "pull": ["I pull the door open.","Kihúzom az ajtót."],
  "push": ["I push the door shut.","Betolom az ajtót."],
  "put": ["I put milk in my coffee.","Tejet teszek a kávémba."],
  "quarter": ["It is a quarter past six.","Negyed hét van."],
  "question": ["Emma asks a good question.","Emma jó kérdést tesz fel."],
  "quiet": ["The house is very quiet.","A ház nagyon csendes."],
  "quite": ["The book is quite good.","A könyv elég jó."],
  "rabbit": ["The rabbit runs very fast.","A nyúl nagyon gyorsan fut."],
  "rainy": ["It is a rainy day.","Esős nap van."],
  "ready": ["I am ready for class.","Készen állok az órára."],
  "real": ["Rita is a real friend.","Rita igazi barát."],
  "red": ["The apple is red.","Az alma piros."],
  "remember": ["I remember your name.","Emlékszem a nevedre."],
  "rest": ["I need a little rest.","Szükségem van egy kis pihenésre."],
  "return": ["We return home tomorrow.","Holnap hazatérünk."],
  "ride": ["Panna can ride her horse.","Panna tudja lovagolni a lovát."],
  "ring": ["I ring Rita every evening.","Minden este felhívom Ritát."],
  "river": ["The river is near Prague.","A folyó Prága közelében van."],
  "road": ["The road is very long.","Az út nagyon hosszú."],
  "run": ["Emma and Panna run fast.","Emma és Panna gyorsan futnak."],
  "sad": ["She is sad today.","Ma szomorú."],
  "safe": ["Flying is very safe.","A repülés nagyon biztonságos."],
  "salad": ["The salad is very fresh today.","A saláta ma nagyon friss."],
  "same": ["We have the same idea.","Ugyanaz az ötletünk."],
  "sandwich": ["I make a sandwich for Ákos.","Csinálok egy szendvicset Ákosnak."],
  "saturday": ["I call Kira on Saturday.","Szombaton felhívom Kirát."],
  "save": ["I save my work now.","Most elmentem a munkámat."],
  "saw": ["Yesterday I saw Kira.","Tegnap láttam Kirát."],
  "school": ["I worked at a school.","Egy iskolában dolgoztam."],
  "screen": ["Look at the screen, please.","Nézz a képernyőre, kérlek."],
  "sea": ["The sea is blue and cold.","A tenger kék és hideg."],
  "seat": ["My seat is by the window.","A helyem az ablaknál van."],
  "second": ["This is the second lesson.","Ez a második óra."],
  "security": ["We wait at security.","A biztonsági ellenőrzésnél várunk."],
  "sell": ["They sell fresh eggs at the market.","Friss tojást árulnak a piacon."],
  "send": ["I send a letter to Margó.","Küldök egy levelet Margónak."],
  "september": ["My students come back in September.","A diákjaim szeptemberben visszajönnek."],
  "seven": ["I teach seven children today.","Ma hét gyereket tanítok."],
  "seventeen": ["She is seventeen years old.","Ő tizenhét éves."],
  "seventy": ["I am seventy years old.","Hetven éves vagyok."],
  "shirt": ["David wears a blue shirt.","David kék inget visel."],
  "shoes": ["My new shoes are black.","Az új cipőm fekete."],
  "shop": ["The shop is near my house.","A bolt a házam közelében van."],
  "show": ["I show my students a book.","Mutatok a diákjaimnak egy könyvet."],
  "sick": ["I feel sick this morning.","Rosszul vagyok ma reggel."],
  "sing": ["The children sing a song.","A gyerekek énekelnek egy dalt."],
  "sit": ["I sit in the garden.","A kertben ülök."],
  "six": ["Kira is six years old.","Kira hatéves."],
  "sixteen": ["My student is sixteen years old.","A tanítványom tizenhat éves."],
  "sixty": ["Margó is sixty years old.","Margó hatvan éves."],
  "size": ["What size do you want?","Milyen méretet szeretne?"],
  "sky": ["The sky is blue today.","Az ég kék ma."],
  "sleep": ["I sleep for eight hours.","Nyolc órát alszom."],
  "sleepy": ["I feel sleepy tonight.","Ma este álmos vagyok."],
  "slow": ["The bus is very slow.","A busz nagyon lassú."],
  "slowly": ["Please speak slowly.","Kérlek, beszélj lassan."],
  "small": ["My garden is very small.","A kertem nagyon kicsi."],
  "smile": ["My family makes me smile.","A családom mosolyra késztet."],
  "snack": ["I want a small snack now.","Kérek egy kis nasit most."],
  "sofa": ["The cat sleeps on the sofa.","A macska a kanapén alszik."],
  "soft": ["The bed is very soft.","Az ágy nagyon puha."],
  "song": ["We sing an old song.","Éneklünk egy régi dalt."],
  "soon": ["I visit Kira soon.","Hamarosan meglátogatom Kirát."],
  "south": ["Spain is in the south.","Spanyolország délen van."],
  "spain": ["Endika is from Spain.","Endika spanyol."],
  "spend": ["I spend a little money today.","Kevés pénzt költök ma."],
  "spoon": ["I eat soup with a spoon.","Kanállal eszem a levest."],
  "sport": ["Football is my favourite sport.","A foci a kedvenc sportom."],
  "square": ["The square is very big.","A tér nagyon nagy."],
  "stand": ["I stand by the window.","Az ablaknál állok."],
  "star": ["I can see one star.","Látok egy csillagot."],
  "start": ["We start the lesson now.","Most kezdjük az órát."],
  "station": ["The station is very near.","Az állomás nagyon közel van."],
  "stay": ["We stay in Denmark.","Dániában maradunk."],
  "stop": ["The bus stops here.","A busz itt megáll."],
  "story": ["Emma reads a good story.","Emma egy jó történetet olvas."],
  "straight": ["The road is very straight.","Az út nagyon egyenes."],
  "strong": ["The coffee is very strong.","A kávé nagyon erős."],
  "sun": ["The sun is very bright.","A nap nagyon fényes."],
  "sunday": ["I walk in the garden on Sunday.","Vasárnap sétálok a kertben."],
  "sunny": ["Today is warm and sunny.","Ma meleg és napos van."],
  "supermarket": ["The supermarket is very near.","A szupermarket nagyon közel van."],
  "sure": ["I am not sure.","Nem vagyok biztos benne."],
  "surprised": ["I was very surprised.","Nagyon meglepődtem."],
  "sweet": ["This cake is too sweet.","Ez a sütemény túl édes."],
  "swim": ["We swim in Lake Balaton.","Úszunk a Balatonban."],
  "switzerland": ["Switzerland is very beautiful.","Svájc nagyon szép."],
  "table": ["We sit at the table.","Az asztalnál ülünk."],
  "taste": ["I taste the soup slowly.","Lassan megkóstolom a levest."],
  "taxi": ["We take a taxi.","Taxival megyünk."],
  "television": ["We watch a film on television.","Filmet nézünk a televízióban."],
  "tell": ["Tell me about Prague.","Mesélj Prágáról."],
  "ten": ["The lesson starts at ten.","Az óra tízkor kezdődik."],
  "terrible": ["The film was terrible.","A film szörnyű volt."],
  "thank": ["Thank you very much.","Nagyon köszönöm."],
  "third": ["It is my third visit.","Ez a harmadik látogatásom."],
  "thirsty": ["Panna is thirsty after the ride.","Panna szomjas a lovaglás után."],
  "thirteen": ["Emma is thirteen years old.","Emma tizenhárom éves."],
  "thirty": ["The lesson lasts thirty minutes.","Az óra harminc percig tart."],
  "thousand": ["I have a thousand photos.","Ezer fényképem van."],
  "thursday": ["I clean the house on Thursday.","Csütörtökön kitakarítom a házat."],
  "together": ["We learn English together.","Együtt tanulunk angolul."],
  "toilet": ["Where is the toilet, please?","Hol van a mosdó, kérlek?"],
  "tomato": ["I put a tomato in the salad.","Teszek egy paradicsomot a salátába."],
  "tooth": ["I clean my teeth every morning.","Minden reggel fogat mosok."],
  "top": ["We stand at the top.","A tetején állunk."],
  "tourist": ["Many tourists visit Budapest.","Sok turista jön Budapestre."],
  "towel": ["The towel is soft and dry.","A törölköző puha és száraz."],
  "town": ["Our town is very quiet.","A városunk nagyon csendes."],
  "tree": ["A big tree stands outside.","Egy nagy fa áll kint."],
  "trousers": ["My trousers are too long.","A nadrágom túl hosszú."],
  "true": ["Is that story true?","Igaz az a történet?"],
  "try": ["Please try the new word.","Próbáld ki az új szót."],
  "tuesday": ["I have a lesson on Tuesday.","Kedden van egy órám."],
  "turn": ["Turn left at the corner.","Fordulj balra a sarkon."],
  "turn off": ["Please turn off the camera.","Kérlek, kapcsold ki a kamerát."],
  "turn on": ["I turn on my laptop.","Bekapcsolom a laptopomat."],
  "twelve": ["We stop at twelve o'clock.","Tizenkét órakor megállunk."],
  "twenty": ["I know twenty new words.","Húsz új szót tudok."],
  "umbrella": ["I take my umbrella today.","Ma viszem az esernyőmet."],
  "use": ["I use my laptop every day.","Minden nap használom a laptopomat."],
  "vegetable": ["I buy a vegetable at the market.","Veszek egy zöldséget a piacon."],
  "very": ["I am very happy.","Nagyon boldog vagyok."],
  "video": ["I watch a short video.","Nézek egy rövid videót."],
  "village": ["Agárd is a small village.","Agárd egy kis falu."],
  "wait": ["Please wait a moment.","Kérlek, várj egy pillanatot."],
  "wait for": ["I will wait for you.","Megvárlak."],
  "wake up": ["I wake up at six.","Hatkor ébredek fel."],
  "walk": ["I walk in the garden.","Sétálok a kertben."],
  "wall": ["The photo is on the wall.","A fénykép a falon van."],
  "warm": ["The sun is warm today.","A nap meleg ma."],
  "was": ["Yesterday I was at home.","Tegnap otthon voltam."],
  "wash": ["I wash the cups after coffee.","Kávé után elmosom a csészéket."],
  "watch": ["We watch the news together.","Együtt nézzük a híreket."],
  "wear": ["I wear a warm coat.","Meleg kabátot viselek."],
  "wednesday": ["I meet Rita on Wednesday.","Szerdán találkozom Ritával."],
  "week": ["I call Kira this week.","Ezen a héten felhívom Kirát."],
  "well": ["I feel well today.","Ma jól érzem magam."],
  "went": ["Yesterday I went to Prague.","Tegnap Prágába mentem."],
  "west": ["Belgium is in the west.","Belgium nyugaton van."],
  "wet": ["The grass is very wet.","A fű nagyon nedves."],
  "white": ["The snow is white.","A hó fehér."],
  "wide": ["The road is very wide.","Az út nagyon széles."],
  "wife": ["Marlene is David's wife.","Marlene David felesége."],
  "win": ["I hope you win today.","Remélem, ma nyersz."],
  "windy": ["It is cold and windy.","Hideg és szeles van."],
  "wonderful": ["The trip was wonderful.","Az utazás csodálatos volt."],
  "word": ["This is a new word.","Ez egy új szó."],
  "worry": ["Don't worry about me.","Ne aggódj miattam."],
  "write": ["Please write your name here.","Kérlek, írd ide a neved."],
  "wrong": ["This answer is wrong.","Ez a válasz rossz."],
  "year": ["I visit Kira this year.","Idén meglátogatom Kirát."],
  "yellow": ["The flowers are yellow.","A virágok sárgák."],
  "zero": ["The number starts with zero.","A szám nullával kezdődik."],
};
