// Natural example sentences (EN + HU), tied to Marta's world where possible.
// Curated overrides for common / awkward words; the generator falls back to a
// grammar-safe template (see build-data.mjs) for anything not listed here.
// Keyed by headword (lowercase). Hungarian still flagged for human review.

export const EXAMPLES = {
  // greetings & core
  "hello": ["Hello! I'm Marta.", "Szia! Marta vagyok."],
  "goodbye": ["Goodbye! See you soon.", "Viszlát! Hamarosan találkozunk."],
  "please": ["Can you help me, please?", "Tudsz segíteni, kérlek?"],
  "thank you": ["Thank you very much.", "Nagyon köszönöm."],
  "sorry": ["Sorry, I don't understand.", "Elnézést, nem értem."],
  "yes": ["Yes, I would like some tea.", "Igen, kérnék egy teát."],
  "no": ["No, thank you.", "Nem, köszönöm."],
  "name": ["My name is Marta.", "A nevem Marta."],
  "fine": ["I'm fine, thank you.", "Jól vagyok, köszönöm."],
  "welcome": ["Welcome to my home!", "Üdvözöllek az otthonomban!"],
  // pronouns / grammar words
  "i": ["I live in Hungary.", "Magyarországon élek."],
  "you": ["Where are you from?", "Honnan jössz?"],
  "he": ["He is my nephew.", "Ő az unokaöcsém."],
  "she": ["She is my niece, Kira.", "Ő az unokahúgom, Kira."],
  "we": ["We are a big family.", "Nagy család vagyunk."],
  "they": ["They live in Denmark.", "Ők Dániában élnek."],
  "it": ["It is a nice day.", "Szép nap van."],
  "be": ["I am happy today.", "Ma boldog vagyok."],
  "this": ["This is my sister.", "Ez a nővérem."],
  "that": ["That is a lovely photo.", "Az egy szép fénykép."],
  "these": ["These are my books.", "Ezek az én könyveim."],
  "those": ["Those are Kira's shoes.", "Azok Kira cipői."],
  "my": ["This is my family.", "Ez az én családom."],
  "your": ["What is your name?", "Hogy hívnak?"],
  "his": ["His name is Endika.", "Az ő neve Endika."],
  "her": ["Her name is Kira.", "Az ő neve Kira."],
  "have": ["I have two sisters.", "Két nővérem van."],
  "a": ["I am a teacher.", "Tanár vagyok."],
  "an": ["It is an apple.", "Ez egy alma."],
  "the": ["The coffee is hot.", "A kávé forró."],
  "and": ["I like tea and coffee.", "Szeretem a teát és a kávét."],
  "but": ["I like tea, but not coffee.", "Szeretem a teát, de a kávét nem."],
  "because": ["I'm happy because you are here.", "Boldog vagyok, mert itt vagy."],
  "so": ["It's late, so I go home.", "Késő van, úgyhogy hazamegyek."],
  "very": ["It is very nice.", "Nagyon szép."],
  "and you": ["I'm fine. And you?", "Jól vagyok. És te?"],
  // question words
  "what": ["What is your name?", "Hogy hívnak?"],
  "where": ["Where do you live?", "Hol laksz?"],
  "how": ["How are you?", "Hogy vagy?"],
  "who": ["Who is that?", "Ki az?"],
  "when": ["When do we meet?", "Mikor találkozunk?"],
  "why": ["Why do you like it?", "Miért szereted?"],
  "which": ["Which bus goes to the centre?", "Melyik busz megy a központba?"],
  // family
  "family": ["I love my family.", "Szeretem a családomat."],
  "mother": ["My mother is kind.", "Az anyám kedves."],
  "father": ["My father is retired.", "Az apám nyugdíjas."],
  "sister": ["I have one sister, Margó.", "Egy nővérem van, Margó."],
  "brother": ["My brother lives near me.", "A bátyám a közelemben lakik."],
  "niece": ["My niece lives in Denmark.", "Az unokahúgom Dániában él."],
  "husband": ["Her husband is called Endre.", "A férjét Endrének hívják."],
  "child": ["I teach children online.", "Gyerekeket tanítok online."],
  "friend": ["She is a good friend.", "Ő egy jó barát."],
  "people": ["I love the people in my family.", "Szeretem a családom tagjait."],
  "man": ["That man is my brother.", "Az a férfi a bátyám."],
  "woman": ["The woman is my sister.", "A nő a nővérem."],
  "baby": ["The baby is very small.", "A baba nagyon kicsi."],
  // countries / languages
  "hungary": ["I am from Hungary.", "Magyarországról jöttem."],
  "english": ["I am learning English.", "Angolul tanulok."],
  "language": ["English is our shared language.", "Az angol a közös nyelvünk."],
  "speak": ["I speak a little English.", "Beszélek egy kicsit angolul."],
  "live": ["I live in Hungary.", "Magyarországon élek."],
  "work": ["I work with children.", "Gyerekekkel dolgozom."],
  "come": ["I come from Hungary.", "Magyarországról jövök."],
  // daily life / verbs
  "get up": ["I get up at seven.", "Hétkor kelek."],
  "eat": ["I eat breakfast at eight.", "Nyolckor reggelizem."],
  "drink": ["I drink coffee in the morning.", "Reggel kávét iszom."],
  "go": ["I go to the market on Monday.", "Hétfőn piacra megyek."],
  "read": ["I like to read in the evening.", "Este szeretek olvasni."],
  "make": ["I make coffee for my sister.", "Kávét készítek a nővéremnek."],
  "cook": ["I love to cook for my family.", "Imádok főzni a családomnak."],
  "help": ["Could you help me, please?", "Tudna segíteni, kérem?"],
  "want": ["I want to learn English.", "Angolul akarok tanulni."],
  "need": ["I need a ticket, please.", "Egy jegyet kérek."],
  "like": ["I like cooking and reading.", "Szeretek főzni és olvasni."],
  "love": ["I love my family.", "Szeretem a családomat."],
  "give": ["Please give me the menu.", "Kérem, adja ide az étlapot."],
  "take": ["I take the bus to the centre.", "Busszal megyek a központba."],
  "know": ["I know a little English.", "Tudok egy kicsit angolul."],
  "think": ["I think it is beautiful.", "Szerintem gyönyörű."],
  "say": ["How do you say this in English?", "Hogy mondják ezt angolul?"],
  "ask": ["Can I ask a question?", "Kérdezhetek valamit?"],
  "talk": ["I want to talk to Endika.", "Szeretnék beszélni Endikával."],
  "understand": ["I don't understand. Please repeat.", "Nem értem. Kérlek, ismételd."],
  "learn": ["I want to learn English for my family.", "A családomért akarok angolul tanulni."],
  "teach": ["I teach Hungarian online.", "Magyart tanítok online."],
  // home
  "home": ["I am at home now.", "Most otthon vagyok."],
  "house": ["Our house has a garden.", "A házunknak van kertje."],
  "kitchen": ["I cook in the kitchen.", "A konyhában főzök."],
  "room": ["There are three rooms.", "Három szoba van."],
  "door": ["Please close the door.", "Kérlek, csukd be az ajtót."],
  "window": ["The window is open.", "Az ablak nyitva van."],
  // food (many uncountable)
  "food": ["The food is delicious.", "Az étel finom."],
  "water": ["Could I have some water, please?", "Kaphatnék egy kis vizet, kérem?"],
  "coffee": ["I drink coffee every morning.", "Minden reggel kávét iszom."],
  "tea": ["Would you like some tea?", "Kérsz egy kis teát?"],
  "milk": ["I take milk in my coffee.", "Tejjel iszom a kávét."],
  "bread": ["I buy fresh bread.", "Friss kenyeret veszek."],
  "cheese": ["I like cheese with bread.", "Szeretem a sajtot kenyérrel."],
  "apple": ["I eat an apple every day.", "Minden nap eszem egy almát."],
  "soup": ["I'd like the soup, please.", "A levest kérném."],
  "cake": ["Would you like some cake?", "Kérsz egy kis süteményt?"],
  "breakfast": ["I have breakfast at eight.", "Nyolckor reggelizem."],
  "lunch": ["We have lunch together.", "Együtt ebédelünk."],
  "dinner": ["Dinner is at seven.", "A vacsora hétkor van."],
  "buy": ["I buy food at the market.", "A piacon veszek élelmiszert."],
  // time / weather / plans
  "time": ["What time is it?", "Mennyi az idő?"],
  "today": ["Today is a good day.", "Ma jó nap van."],
  "tomorrow": ["I will call Kira tomorrow.", "Holnap felhívom Kirát."],
  "weekend": ["I am free at the weekend.", "Hétvégén ráérek."],
  "weather": ["The weather is nice today.", "Ma szép idő van."],
  "plan": ["What are your plans?", "Mik a terveid?"],
  "meet": ["Let's meet on Sunday.", "Találkozzunk vasárnap."],
  "can": ["I can cook well.", "Jól tudok főzni."],
  // phone / calls
  "call": ["I call my niece on Sundays.", "Vasárnaponként hívom az unokahúgomat."],
  "phone": ["I use my phone to call Kira.", "A telefonommal hívom Kirát."],
  "hear": ["Can you hear me?", "Hallasz engem?"],
  "see": ["Can you see me?", "Látsz engem?"],
  "repeat": ["Could you repeat that, please?", "Meg tudná ismételni, kérem?"],
  // hobbies / opinions
  "hobby": ["My hobby is cooking.", "A hobbim a főzés."],
  "book": ["I am reading a good book.", "Egy jó könyvet olvasok."],
  "music": ["I like quiet music.", "Szeretem a halk zenét."],
  "enjoy": ["I enjoy cooking with Kira.", "Élvezem a főzést Kirával."],
  "favourite": ["Cooking is my favourite hobby.", "A főzés a kedvenc hobbim."],
  "beautiful": ["The lake is beautiful.", "A tó gyönyörű."],
  // town / transport
  "street": ["I live on a quiet street.", "Egy csendes utcában lakom."],
  "bus": ["Which bus goes to the centre?", "Melyik busz megy a központba?"],
  "train": ["The train is very fast.", "A vonat nagyon gyors."],
  "car": ["Ákos drives the car.", "Ákos vezeti az autót."],
  "ticket": ["I need a ticket, please.", "Egy jegyet kérek."],
  "left": ["Turn left at the corner.", "A saroknál fordulj balra."],
  "right": ["Turn right at the church.", "A templomnál fordulj jobbra."],
  // services / hotel
  "restaurant": ["We eat at a nice restaurant.", "Egy szép étteremben eszünk."],
  "hotel": ["The hotel is near the station.", "A szálloda az állomás közelében van."],
  "menu": ["Could I have the menu, please?", "Megkaphatnám az étlapot, kérem?"],
  "bill": ["Could I have the bill, please?", "Megkaphatnám a számlát, kérem?"],
  "help": ["Could you help me, please?", "Tudna segíteni, kérem?"],
  // teaching / technology
  "lesson": ["Let's start today's lesson.", "Kezdjük a mai órát."],
  "camera": ["Please turn your camera on.", "Kérlek, kapcsold be a kamerát."],
  "microphone": ["Please turn your microphone on.", "Kérlek, kapcsold be a mikrofont."],
  "computer": ["I teach on my computer.", "A számítógépemen tanítok."],
  "student": ["My student is a kind child.", "A diákom egy kedves gyerek."],
  "excellent": ["Excellent! Well done!", "Kiváló! Ügyes vagy!"],
  // past / travel
  "visit": ["I visited my sister yesterday.", "Tegnap meglátogattam a nővéremet."],
  "yesterday": ["Yesterday I was at home.", "Tegnap otthon voltam."],
  "travel": ["My friend Rita travels for work.", "A barátnőm, Rita munka miatt utazik."],
  "trip": ["How was your trip?", "Milyen volt az utad?"],
  "passport": ["Here is my passport.", "Itt az útlevelem."],
  "suitcase": ["My suitcase is heavy.", "A bőröndöm nehéz."],
  // airport / flying (emotional core)
  "airport": ["I am at the airport.", "A reptéren vagyok."],
  "flight": ["My flight is at ten.", "A járatom tízkor indul."],
  "gate": ["Where is my gate, please?", "Hol van a kapum, kérem?"],
  "plane": ["This is my first plane trip.", "Ez az első repülőutam."],
  "afraid": ["I am afraid of flying.", "Félek a repüléstől."],
  "nervous": ["I feel a little nervous.", "Kicsit ideges vagyok."],
  "blanket": ["Could I have a blanket, please?", "Kaphatnék egy takarót, kérem?"],
  "land": ["When will we land?", "Mikor szállunk le?"],
  "calm": ["I try to stay calm.", "Próbálok nyugodt maradni."],
  // feelings
  "happy": ["I am happy to see you.", "Örülök, hogy látlak."],
  "tired": ["I am a little tired today.", "Ma kicsit fáradt vagyok."],
  "glad": ["I am glad you are here.", "Örülök, hogy itt vagy."],
  // numbers
  "one": ["I have one sister.", "Egy nővérem van."],
  "two": ["Two coffees, please.", "Két kávét kérek."],
  "three": ["We have three rooms.", "Három szobánk van."],
  // function & abstract words (avoid awkward templates)
  "from": ["I'm from Hungary.", "Magyarországról jöttem."],
  "our": ["This is our house.", "Ez a mi házunk."],
  "their": ["Their children live abroad.", "A gyerekeik külföldön élnek."],
  "very": ["It is very nice.", "Nagyon szép."],
  "some": ["I'd like some water.", "Kérnék egy kis vizet."],
  "any": ["Do you have any tea?", "Van teád?"],
  "much": ["How much is it?", "Mennyibe kerül?"],
  "many": ["How many people are coming?", "Hányan jönnek?"],
  "me": ["Can you hear me?", "Hallasz engem?"],
  "him": ["I like him very much.", "Nagyon kedvelem őt."],
  "them": ["I visit them every summer.", "Minden nyáron meglátogatom őket."],
  "in": ["The keys are in the kitchen.", "A kulcsok a konyhában vannak."],
  "on": ["The book is on the table.", "A könyv az asztalon van."],
  "under": ["The cat is under the chair.", "A macska a szék alatt van."],
  "next to": ["The shop is next to the bank.", "A bolt a bank mellett van."],
  "here": ["Please sit here.", "Kérlek, ülj ide."],
  "there": ["The station is over there.", "Az állomás ott van."],
  "too": ["I'm happy, and my sister is happy too.", "Boldog vagyok, és a nővérem is."],
  "also": ["I speak Hungarian and also a little English.", "Beszélek magyarul és egy kicsit angolul is."],
  "only": ["I have only one brother.", "Csak egy bátyám van."],
  "maybe": ["Maybe we can meet on Sunday.", "Talán találkozhatunk vasárnap."],
  "really": ["I really like this.", "Nagyon tetszik ez."],
  "just": ["I've just made coffee.", "Épp most készítettem kávét."],
  "about": ["Let's talk about your trip.", "Beszéljünk az utadról."],
  "up": ["I get up at seven.", "Hétkor kelek."],
  "down": ["Please sit down.", "Kérlek, ülj le."],
  "out": ["Let's go out for a walk.", "Menjünk ki sétálni."],
  "with": ["I live with my partner.", "A párommal élek."],
  "for": ["This is for you.", "Ez neked van."],
  "at": ["The lesson is at ten.", "Az óra tízkor van."],
  "to": ["I go to the market on Monday.", "Hétfőn a piacra megyek."],
  "of": ["She is a friend of the family.", "Ő a család barátja."],
  "by": ["I travel by train.", "Vonattal utazom."],
  "over": ["The lesson is over.", "Vége az órának."],
  "behind": ["The garden is behind the house.", "A kert a ház mögött van."],
  "into": ["Please come into the kitchen.", "Kérlek, gyere be a konyhába."],
  "through": ["We walked through the park.", "Átsétáltunk a parkon."],
  "around": ["It's just around the corner.", "Ott van a sarok mögött."],
  "then": ["First we eat, then we talk.", "Előbb eszünk, aztán beszélgetünk."],
  "way": ["Is this the way to the station?", "Erre van az állomás?"],
  "thing": ["I have one more thing to say.", "Még egy dolgot mondanék."],
  "part": ["This is my favourite part.", "Ez a kedvenc részem."],
  "side": ["The shop is on the other side.", "A bolt a másik oldalon van."],
  "end": ["The station is at the end of the street.", "Az állomás az utca végén van."],
  "still": ["I still remember it.", "Még mindig emlékszem rá."],
  "already": ["I've already eaten, thank you.", "Már ettem, köszönöm."],
  // --- v1.9 curated: identity, family roles & descriptors (anchored to Marta's world) ---
  "teacher": ["I am a teacher.", "Tanár vagyok."],
  "retired": ["I am a retired teacher.", "Nyugdíjas tanár vagyok."],
  "mum": ["I call my mum every week.", "Minden héten felhívom anyát."],
  "dad": ["My dad likes the garden.", "Apa szereti a kertet."],
  "daughter": ["She is my daughter.", "Ő a lányom."],
  "son": ["He is my son.", "Ő a fiam."],
  "partner": ["This is my partner.", "Ez a párom."],
  "boyfriend": ["Endika is Kira's boyfriend.", "Endika Kira barátja."],
  "girlfriend": ["Marlene is David's girlfriend.", "Marlene David barátnője."],
  "nephew": ["David is my nephew.", "David az unokaöcsém."],
  "aunt": ["Aunt Eva cooks for Christmas.", "Eva néni karácsonyra főz."],
  "uncle": ["He is my uncle.", "Ő a nagybátyám."],
  "grandmother": ["I am a grandmother.", "Nagymama vagyok."],
  "grandfather": ["He is a grandfather.", "Ő nagypapa."],
  "old": ["My house is very old.", "A házam nagyon régi."],
  "young": ["My students are young.", "A diákjaim fiatalok."],
  "married": ["Kira and Endika are married.", "Kira és Endika házasok."],
  "single": ["My nephew is single.", "Az unokaöcsém egyedülálló."],
  "tall": ["My son is very tall.", "A fiam nagyon magas."],
  "short": ["The lesson is short.", "A lecke rövid."],
  "kind": ["Endika is very kind.", "Endika nagyon kedves."],
  "funny": ["My students are funny.", "A diákjaim viccesek."],
  "scared": ["I am scared of flying.", "Félek a repüléstől."],
  "hungarian": ["I am Hungarian.", "Magyar vagyok."],
  "spanish": ["Endika is Spanish.", "Endika spanyol."],
  "danish": ["Kira speaks Danish.", "Kira beszél dánul."],
  "german": ["I don't speak German.", "Nem beszélek németül."],
  "morning": ["I drink coffee in the morning.", "Reggel kávét iszom."],
  "afternoon": ["We talk in the afternoon.", "Délután beszélgetünk."],
  "evening": ["I teach in the evening.", "Este tanítok."],
  "garden": ["We sit in the garden.", "A kertben ülünk."],
  "country": ["Denmark is a beautiful country.", "Dánia gyönyörű ország."],
  "city": ["Prague is a lovely city.", "Prága csodás város."],
  "always": ["I always drink coffee.", "Mindig kávét iszom."],
  "usually": ["I usually teach on Mondays.", "Hétfőnként általában tanítok."],
  "often": ["I often call my family.", "Gyakran felhívom a családomat."],
  "sometimes": ["I sometimes travel.", "Néha utazom."],
  "never": ["I never drink cola.", "Soha nem iszom kólát."],
};
