// Functional grammar cards — brief, bilingual, revisited (spiral).
// [id, unit, titleEn, titleHu, purposeEn, explainEn, explainHu, examples[[en,hu]...], useWhenEn, checkQ, checkA]
export const GRAMMAR = [
  ["gr_be", "u01", "The verb 'be'", "A 'be' (lenni) ige",
    "Say who and what someone is.",
    "Use am with I, is with he/she/it, are with you/we/they. Short forms: I'm, you're, he's.",
    "Az I mellett am, a he/she/it mellett is, a you/we/they mellett are áll. Rövid alakok: I'm, you're, he's.",
    [["I am Marta.", "Marta vagyok."], ["She is my niece.", "Ő az unokahúgom."], ["We are from Hungary.", "Magyarországról jövünk."]],
    "Use this when you introduce yourself or describe people.",
    "Choose: I ___ happy. (am / is)", "am"],
  ["gr_pronouns", "u01", "Subject pronouns", "Alanyi névmások",
    "Say who does something.",
    "I, you, he, she, it, we, they replace names. Use he for a man, she for a woman.",
    "Az I, you, he, she, it, we, they a nevek helyett áll. He = férfi, she = nő.",
    [["He is Spanish.", "Ő spanyol."], ["They live in Denmark.", "Ők Dániában élnek."]],
    "Use this to talk about other people.",
    "Endika is a man. He or she?", "he"],
  ["gr_questions_wh", "u01", "Question words", "Kérdőszavak",
    "Ask for information.",
    "What asks about things, Where about places, How about the way. The verb comes after the question word.",
    "A what dolgokra, a where helyre, a how módra kérdez. A kérdőszó után jön az ige.",
    [["What is your name?", "Hogy hívnak?"], ["Where are you from?", "Honnan jössz?"], ["How are you?", "Hogy vagy?"]],
    "Use this to start a conversation with questions.",
    "___ are you from? (What / Where)", "Where"],
  ["gr_articles", "u01", "a / an", "a / an (egy)",
    "Talk about one thing.",
    "Use a before a consonant sound, an before a vowel sound: a teacher, an apple.",
    "Mássalhangzó előtt a, magánhangzó előtt an: a teacher, an apple.",
    [["I am a teacher.", "Tanár vagyok."], ["It is an apple.", "Ez egy alma."]],
    "Use this with jobs and single things.",
    "___ egg (a / an)", "an"],
  ["gr_possadj", "u02", "Possessive adjectives", "Birtokos névmások",
    "Say whose something is.",
    "my, your, his, her, our, their show who owns something. His for a man, her for a woman.",
    "A my, your, his, her, our, their megmutatja, kié valami. His = férfié, her = nőé.",
    [["This is my family.", "Ez az én családom."], ["Her name is Kira.", "Az ő neve Kira."]],
    "Use this to talk about your family and things.",
    "Kira is a woman. ___ name. (his / her)", "her"],
  ["gr_poss_s", "u02", "Possessive 's", "Birtokos 's",
    "Show that something belongs to a person.",
    "Add 's to a name: Kira's boyfriend = the boyfriend of Kira.",
    "Tegyél 's-t a név után: Kira's boyfriend = Kira barátja.",
    [["Endika is Kira's boyfriend.", "Endika Kira barátja."], ["This is Marta's house.", "Ez Marta háza."]],
    "Use this to say who someone belongs to in the family.",
    "the sister of Marta = Marta___ sister", "'s"],
  ["gr_have", "u02", "have / has", "have / has (van neki)",
    "Say what people have.",
    "Use have with I/you/we/they and has with he/she/it.",
    "Az I/you/we/they mellett have, a he/she/it mellett has áll.",
    [["I have two sisters.", "Két nővérem van."], ["She has a nice house.", "Szép háza van."]],
    "Use this to talk about family and things you own.",
    "He ___ a brother. (have / has)", "has"],
  ["gr_plural", "u02", "Plural nouns", "Többes szám",
    "Talk about more than one.",
    "Add -s for more than one: one sister, two sisters. Some words change: child → children.",
    "Több dologhoz tegyél -s-t: one sister, two sisters. Néhány szó változik: child → children.",
    [["I have three brothers.", "Három bátyám van."], ["Two coffees, please.", "Két kávét kérek."]],
    "Use this to count people and things.",
    "one book, two ___", "books"],
  ["gr_presentsimple", "u04", "Present simple", "Egyszerű jelen",
    "Talk about routines and facts.",
    "Use the base verb: I get up, they work. Add -s for he/she/it: she works.",
    "Alap ige: I get up, they work. He/she/it mellett -s: she works.",
    [["I get up at seven.", "Hétkor kelek."], ["She works in Belgium.", "Belgiumban dolgozik."]],
    "Use this to describe your day.",
    "She ___ (work) every day.", "works"],
  ["gr_dodoes", "u04", "do / does questions", "do / does kérdések",
    "Ask about routines.",
    "Use Do you...? and Does he/she...? Do not add -s to the main verb: Does she work?",
    "Do you...? és Does he/she...? A fő igéhez ne tegyél -s-t: Does she work?",
    [["Do you like coffee?", "Szereted a kávét?"], ["Does she live here?", "Itt lakik?"]],
    "Use this to ask people about their routines.",
    "___ you like tea? (Do / Does)", "Do"],
  ["gr_frequency", "u04", "always, usually, sometimes, never", "gyakorisági határozók",
    "Say how often something happens.",
    "These words usually come before the main verb: I always drink coffee.",
    "Ezek a szavak általában a fő ige előtt állnak: I always drink coffee.",
    [["I usually get up early.", "Általában korán kelek."], ["She never eats meat.", "Soha nem eszik húst."]],
    "Use this to describe habits.",
    "Word order: I / coffee / drink / always → ?", "I always drink coffee"],
  ["gr_thereis", "u04", "there is / there are", "there is / there are (van / vannak)",
    "Say what exists in a place.",
    "There is for one thing, there are for more than one: There is a garden. There are two rooms.",
    "Egy dologhoz there is, többhöz there are: There is a garden. There are two rooms.",
    [["There is a kitchen.", "Van egy konyha."], ["There are two bedrooms.", "Két hálószoba van."]],
    "Use this to describe your home.",
    "___ three chairs. (There is / There are)", "There are"],
  ["gr_someany", "u05", "some / any", "some / any",
    "Talk about amounts.",
    "Use some in positive sentences, any in questions and negatives: I have some bread. Do you have any milk?",
    "Állításban some, kérdésben/tagadásban any: I have some bread. Do you have any milk?",
    [["I'd like some water.", "Kérnék egy kis vizet."], ["Is there any coffee?", "Van kávé?"]],
    "Use this when you shop and cook.",
    "Do you have ___ tea? (some / any)", "any"],
  ["gr_wouldlike", "u05", "I'd like", "Kérnék (I'd like)",
    "Ask politely for something.",
    "I'd like = I would like. It is more polite than I want.",
    "I'd like = I would like. Udvariasabb, mint az I want.",
    [["I'd like a coffee, please.", "Kérnék egy kávét."], ["I'd like the soup.", "A levest kérném."]],
    "Use this in restaurants and shops.",
    "Polite: I ___ a tea, please.", "I'd like"],
  ["gr_can", "u06", "can / can't", "can / can't (tud / nem tud)",
    "Talk about ability and possibility.",
    "Can + base verb: I can swim. Can't = cannot. Questions: Can you help me?",
    "Can + alap ige: I can swim. Can't = cannot. Kérdés: Can you help me?",
    [["I can cook.", "Tudok főzni."], ["Can you help me?", "Tudsz segíteni?"]],
    "Use this to ask for help and say what you can do.",
    "___ you swim? (Can / Do)", "Can"],
  ["gr_goingto", "u06", "going to (plans)", "going to (tervek)",
    "Talk about future plans.",
    "be + going to + verb: I am going to visit Kira.",
    "be + going to + ige: I am going to visit Kira.",
    [["I'm going to travel to Prague.", "Prágába fogok utazni."], ["We are going to cook dinner.", "Vacsorát fogunk főzni."]],
    "Use this to talk about your plans.",
    "I ___ going to call her. (am / do)", "am"],
  ["gr_presentcont", "u06", "Present continuous", "Folyamatos jelen",
    "Talk about now.",
    "be + verb+ing for actions happening now: I am cooking. She is working.",
    "be + ige+ing a most történő cselekvésre: I am cooking. She is working.",
    [["I am reading a book.", "Könyvet olvasok éppen."], ["They are watching a film.", "Filmet néznek éppen."]],
    "Use this to say what is happening right now.",
    "Right now I ___ (cook).", "am cooking"],
  ["gr_prepositions_time", "u06", "at / on / in (time)", "at / on / in (idő)",
    "Say when something happens.",
    "at for times (at seven), on for days (on Monday), in for months (in July).",
    "at időpontra (at seven), on napra (on Monday), in hónapra (in July).",
    [["The lesson is at ten.", "Az óra tízkor van."], ["I'm free on Saturday.", "Szombaton ráérek."]],
    "Use this to make plans.",
    "___ Monday (at / on / in)", "on"],
  ["gr_object_pronouns", "u07", "Object pronouns", "Tárgyi névmások",
    "Replace the person you talk about.",
    "me, you, him, her, it, us, them come after the verb: Can you hear me?",
    "me, you, him, her, it, us, them az ige után áll: Can you hear me?",
    [["Can you hear me?", "Hallasz engem?"], ["I like him.", "Kedvelem őt."]],
    "Use this on phone and video calls.",
    "Can you hear ___? (I / me)", "me"],
  ["gr_likeing", "u08", "like + -ing", "like + -ing",
    "Talk about activities you enjoy.",
    "like/love/enjoy + verb+ing: I like cooking. She loves reading.",
    "like/love/enjoy + ige+ing: I like cooking. She loves reading.",
    [["I love cooking.", "Imádok főzni."], ["He enjoys swimming.", "Élvez úszni."]],
    "Use this to talk about hobbies.",
    "I like ___ (read).", "reading"],
  ["gr_imperatives", "u09", "Imperatives", "Felszólítás",
    "Give a simple instruction.",
    "Use the base verb alone: Turn left. Wait here. Add please to be polite.",
    "Csak az alap ige: Turn left. Wait here. Udvariasan: tegyél please-t.",
    [["Turn right at the corner.", "A saroknál fordulj jobbra."], ["Please wait a moment.", "Kérlek, várj egy pillanatot."]],
    "Use this to give and understand directions.",
    "Give a direction: ___ left. (Turn / Turning)", "Turn"],
  ["gr_could_requests", "u10", "Could you...? / Could I...?", "Could you...? / Could I...?",
    "Make polite requests.",
    "Could you help me? asks someone to do something. Could I have...? asks for something for yourself.",
    "Could you help me? = kérsz vkit vmire. Could I have...? = kérsz magadnak vmit.",
    [["Could you help me, please?", "Tudna segíteni, kérem?"], ["Could I have some water?", "Kaphatnék egy kis vizet?"]],
    "Use this in shops, hotels and on the plane.",
    "Polite request for water: Could I ___ some water?", "have"],
  ["gr_waswere", "u12", "was / were", "was / were (volt)",
    "Talk about the past with 'be'.",
    "was with I/he/she/it, were with you/we/they: I was at home. They were happy.",
    "was: I/he/she/it, were: you/we/they. I was at home. They were happy.",
    [["I was at my sister's house.", "A nővérem házában voltam."], ["The weather was nice.", "Szép idő volt."]],
    "Use this to talk about yesterday.",
    "They ___ happy. (was / were)", "were"],
  ["gr_pastsimple", "u12", "Past simple", "Egyszerű múlt",
    "Talk about finished actions.",
    "Add -ed to many verbs: visited, cooked. Some change: go → went, have → had, see → saw.",
    "Sok igéhez -ed: visited, cooked. Néhány változik: go → went, have → had, see → saw.",
    [["I visited my sister.", "Meglátogattam a nővéremet."], ["We went to Prague.", "Prágába mentünk."]],
    "Use this to tell a short story about the past.",
    "Yesterday I ___ (visit) Kira.", "visited"],
  ["gr_needhaveto", "u13", "need to / have to", "need to / have to (kell)",
    "Say what is necessary.",
    "need to / have to + base verb: I need to pack. I have to check in.",
    "need to / have to + alap ige: I need to pack. I have to check in.",
    [["I need to buy a ticket.", "Jegyet kell vennem."], ["We have to be early.", "Korán kell odaérnünk."]],
    "Use this to plan a trip.",
    "I ___ to pack. (need / needs)", "need"],
  ["gr_conjunctions", "u03", "and, but, because", "and, but, because",
    "Join your ideas.",
    "and adds, but shows a difference, because gives a reason.",
    "and hozzáad, but ellentétet mutat, because okot ad.",
    [["I like tea but I don't like coffee.", "Szeretem a teát, de a kávét nem."], ["I'm happy because you're here.", "Boldog vagyok, mert itt vagy."]],
    "Use this to make longer sentences.",
    "I'm tired ___ I worked a lot. (but / because)", "because"],
];
