// Lexicon source data for "Mirella tante" — Marta's English course.
// Curated productive & receptive vocabulary with Hungarian translations.
// Format per entry: [headword, hu, partOfSpeech, theme, firstLesson, acceptedForms?]
// Hungarian is best-effort and flagged for human review (see HUNGARIAN_REVIEW_QUEUE.csv).
// Themes: greetings, identity, family, countries, daily-life, home, food, shopping,
//         time, weather, plans, phone, hobbies, opinions, town, transport, services,
//         hotel, teaching, technology, past, travel, airport, flying, feelings, numbers,
//         conversation, health, body, colours.

export const PRODUCTIVE = [
  // ---- Unit 1: greetings, identity ----
  ["hello", "szia / jó napot", "phrase", "greetings", "u01-l01"],
  ["hi", "szia", "phrase", "greetings", "u01-l01"],
  ["goodbye", "viszlát", "phrase", "greetings", "u01-l01"],
  ["bye", "szia (búcsú)", "phrase", "greetings", "u01-l01"],
  ["good morning", "jó reggelt", "phrase", "greetings", "u01-l01"],
  ["good afternoon", "jó napot", "phrase", "greetings", "u01-l01"],
  ["good evening", "jó estét", "phrase", "greetings", "u01-l01"],
  ["good night", "jó éjszakát", "phrase", "greetings", "u01-l01"],
  ["please", "kérem", "adverb", "greetings", "u01-l01"],
  ["thank you", "köszönöm", "phrase", "greetings", "u01-l01"],
  ["thanks", "kösz", "phrase", "greetings", "u01-l01"],
  ["yes", "igen", "adverb", "greetings", "u01-l01"],
  ["no", "nem", "adverb", "greetings", "u01-l01"],
  ["sorry", "elnézést / bocsánat", "phrase", "greetings", "u01-l01"],
  ["name", "név", "noun", "identity", "u01-l01", ["name", "names"]],
  ["my", "az én ...-m", "adjective", "identity", "u01-l01"],
  ["your", "a te ...-d", "adjective", "identity", "u01-l01"],
  ["I", "én", "pronoun", "identity", "u01-l01"],
  ["you", "te", "pronoun", "identity", "u01-l01"],
  ["he", "ő (férfi)", "pronoun", "identity", "u01-l02"],
  ["she", "ő (nő)", "pronoun", "identity", "u01-l02"],
  ["we", "mi", "pronoun", "identity", "u01-l02"],
  ["they", "ők", "pronoun", "identity", "u01-l02"],
  ["it", "az (dolog)", "pronoun", "identity", "u01-l02"],
  ["be", "lenni", "verb", "identity", "u01-l02", ["am", "is", "are", "be"]],
  ["from", "-ból / -ből", "preposition", "identity", "u01-l01"],
  ["country", "ország", "noun", "identity", "u01-l01", ["country", "countries"]],
  ["city", "város", "noun", "identity", "u01-l01", ["city", "cities"]],
  ["teacher", "tanár / tanárnő", "noun", "identity", "u01-l01", ["teacher", "teachers"]],
  ["retired", "nyugdíjas", "adjective", "identity", "u01-l01"],
  ["nice", "kedves / jó", "adjective", "identity", "u01-l01"],
  ["what", "mi / mit", "pronoun", "conversation", "u01-l01"],
  ["where", "hol", "adverb", "conversation", "u01-l01"],
  ["how", "hogy / hogyan", "adverb", "conversation", "u01-l01"],
  ["who", "ki", "pronoun", "conversation", "u01-l02"],
  ["fine", "jól", "adjective", "greetings", "u01-l01"],
  ["good", "jó", "adjective", "greetings", "u01-l01"],
  ["well", "jól", "adverb", "greetings", "u01-l01"],
  ["and", "és", "conjunction", "conversation", "u01-l02"],
  ["a", "egy", "article", "identity", "u01-l01"],
  ["an", "egy", "article", "identity", "u01-l01"],
  ["the", "a / az", "article", "identity", "u01-l02"],

  // ---- Unit 2: family ----
  ["family", "család", "noun", "family", "u02-l01", ["family", "families"]],
  ["mother", "anya", "noun", "family", "u02-l01", ["mother", "mothers"]],
  ["father", "apa", "noun", "family", "u02-l01", ["father", "fathers"]],
  ["mum", "anyu", "noun", "family", "u02-l01"],
  ["dad", "apu", "noun", "family", "u02-l01"],
  ["parents", "szülők", "noun", "family", "u02-l01"],
  ["sister", "lánytestvér / nővér", "noun", "family", "u02-l01", ["sister", "sisters"]],
  ["brother", "fiútestvér / báty", "noun", "family", "u02-l01", ["brother", "brothers"]],
  ["daughter", "lánya vkinek", "noun", "family", "u02-l01", ["daughter", "daughters"]],
  ["son", "fia vkinek", "noun", "family", "u02-l01", ["son", "sons"]],
  ["husband", "férj", "noun", "family", "u02-l01", ["husband", "husbands"]],
  ["wife", "feleség", "noun", "family", "u02-l02", ["wife", "wives"]],
  ["partner", "élettárs / partner", "noun", "family", "u02-l02", ["partner", "partners"]],
  ["boyfriend", "barát (párkapcsolat)", "noun", "family", "u02-l02", ["boyfriend", "boyfriends"]],
  ["girlfriend", "barátnő (párkapcsolat)", "noun", "family", "u02-l02", ["girlfriend", "girlfriends"]],
  ["niece", "unokahúg", "noun", "family", "u02-l01", ["niece", "nieces"]],
  ["nephew", "unokaöcs", "noun", "family", "u02-l01", ["nephew", "nephews"]],
  ["aunt", "nagynéni", "noun", "family", "u02-l01", ["aunt", "aunts"]],
  ["uncle", "nagybácsi", "noun", "family", "u02-l01", ["uncle", "uncles"]],
  ["grandmother", "nagymama", "noun", "family", "u02-l02", ["grandmother", "grandmothers"]],
  ["grandfather", "nagypapa", "noun", "family", "u02-l02", ["grandfather", "grandfathers"]],
  ["child", "gyerek", "noun", "family", "u02-l01", ["child", "children"]],
  ["friend", "barát", "noun", "family", "u02-l02", ["friend", "friends"]],
  ["have", "van neki / birtokolni", "verb", "family", "u02-l02", ["have", "has", "had"]],
  ["this", "ez", "pronoun", "family", "u02-l02"],
  ["that", "az", "pronoun", "family", "u02-l02"],
  ["these", "ezek", "pronoun", "family", "u02-l02"],
  ["those", "azok", "pronoun", "family", "u02-l02"],
  ["his", "az ő ...-ja (férfi)", "adjective", "family", "u02-l01"],
  ["her", "az ő ...-ja (nő)", "adjective", "family", "u02-l01"],
  ["our", "a mi ...-nk", "adjective", "family", "u02-l02"],
  ["their", "az ő ...-juk", "adjective", "family", "u02-l02"],
  ["old", "öreg / idős", "adjective", "family", "u02-l02"],
  ["young", "fiatal", "adjective", "family", "u02-l02"],
  ["married", "házas", "adjective", "family", "u02-l02"],

  // ---- Unit 3: countries, languages, description ----
  ["Hungary", "Magyarország", "noun", "countries", "u03-l01"],
  ["Hungarian", "magyar", "adjective", "countries", "u03-l01"],
  ["England", "Anglia", "noun", "countries", "u03-l01"],
  ["English", "angol", "adjective", "countries", "u03-l01"],
  ["Spain", "Spanyolország", "noun", "countries", "u03-l01"],
  ["Spanish", "spanyol", "adjective", "countries", "u03-l01"],
  ["Germany", "Németország", "noun", "countries", "u03-l01"],
  ["German", "német", "adjective", "countries", "u03-l01"],
  ["Denmark", "Dánia", "noun", "countries", "u03-l01"],
  ["Danish", "dán", "adjective", "countries", "u03-l01"],
  ["Belgium", "Belgium", "noun", "countries", "u03-l01"],
  ["Switzerland", "Svájc", "noun", "countries", "u03-l01"],
  ["language", "nyelv", "noun", "countries", "u03-l01", ["language", "languages"]],
  ["speak", "beszélni (nyelvet)", "verb", "countries", "u03-l01", ["speak", "speaks", "spoke"]],
  ["live", "lakni / élni", "verb", "countries", "u03-l01", ["live", "lives", "lived"]],
  ["work", "dolgozni / munka", "verb", "daily-life", "u03-l02", ["work", "works", "worked"]],
  ["come", "jönni", "verb", "countries", "u03-l01", ["come", "comes", "came"]],
  ["tall", "magas", "adjective", "identity", "u03-l02"],
  ["short", "alacsony / rövid", "adjective", "identity", "u03-l02"],
  ["kind", "kedves", "adjective", "identity", "u03-l02"],
  ["funny", "vicces", "adjective", "identity", "u03-l02"],
  ["happy", "boldog", "adjective", "feelings", "u03-l02"],
  ["but", "de", "conjunction", "conversation", "u03-l02"],
  ["because", "mert", "conjunction", "conversation", "u03-l02"],
  ["so", "úgyhogy / tehát", "conjunction", "conversation", "u03-l02"],
  ["very", "nagyon", "adverb", "conversation", "u03-l02"],

  // ---- Unit 4: daily life, home ----
  ["day", "nap", "noun", "daily-life", "u04-l01", ["day", "days"]],
  ["morning", "reggel", "noun", "daily-life", "u04-l01"],
  ["afternoon", "délután", "noun", "daily-life", "u04-l01"],
  ["evening", "este", "noun", "daily-life", "u04-l01"],
  ["night", "éjszaka", "noun", "daily-life", "u04-l01"],
  ["get up", "felkelni", "verb", "daily-life", "u04-l01", ["get up", "gets up", "got up"]],
  ["wake up", "felébredni", "verb", "daily-life", "u04-l01", ["wake up", "wakes up", "woke up"]],
  ["eat", "enni", "verb", "food", "u04-l01", ["eat", "eats", "ate"]],
  ["drink", "inni", "verb", "food", "u04-l01", ["drink", "drinks", "drank"]],
  ["sleep", "aludni", "verb", "daily-life", "u04-l01", ["sleep", "sleeps", "slept"]],
  ["go", "menni", "verb", "daily-life", "u04-l01", ["go", "goes", "went"]],
  ["read", "olvasni", "verb", "hobbies", "u04-l02", ["read", "reads"]],
  ["watch", "nézni", "verb", "daily-life", "u04-l02", ["watch", "watches", "watched"]],
  ["walk", "sétálni", "verb", "daily-life", "u04-l02", ["walk", "walks", "walked"]],
  ["home", "otthon", "noun", "home", "u04-l02"],
  ["house", "ház", "noun", "home", "u04-l02", ["house", "houses"]],
  ["room", "szoba", "noun", "home", "u04-l02", ["room", "rooms"]],
  ["kitchen", "konyha", "noun", "home", "u04-l02", ["kitchen", "kitchens"]],
  ["garden", "kert", "noun", "home", "u04-l02", ["garden", "gardens"]],
  ["always", "mindig", "adverb", "daily-life", "u04-l01"],
  ["usually", "általában", "adverb", "daily-life", "u04-l01"],
  ["often", "gyakran", "adverb", "daily-life", "u04-l01"],
  ["sometimes", "néha", "adverb", "daily-life", "u04-l01"],
  ["never", "soha", "adverb", "daily-life", "u04-l01"],
  ["every day", "minden nap", "phrase", "daily-life", "u04-l01"],
  ["there is", "van (ott)", "phrase", "home", "u04-l02"],
  ["there are", "vannak (ott)", "phrase", "home", "u04-l02"],
  ["in", "-ban / -ben", "preposition", "home", "u04-l02"],
  ["on", "-on / -en / -ön", "preposition", "home", "u04-l02"],
  ["under", "alatt", "preposition", "home", "u04-l02"],
  ["next to", "mellett", "preposition", "home", "u04-l02"],

  // ---- Unit 5: food, shopping ----
  ["food", "étel", "noun", "food", "u05-l01"],
  ["water", "víz", "noun", "food", "u05-l01"],
  ["coffee", "kávé", "noun", "food", "u05-l01"],
  ["tea", "tea", "noun", "food", "u05-l01"],
  ["milk", "tej", "noun", "food", "u05-l01"],
  ["bread", "kenyér", "noun", "food", "u05-l01"],
  ["cheese", "sajt", "noun", "food", "u05-l01"],
  ["egg", "tojás", "noun", "food", "u05-l01", ["egg", "eggs"]],
  ["apple", "alma", "noun", "food", "u05-l01", ["apple", "apples"]],
  ["soup", "leves", "noun", "food", "u05-l01"],
  ["meat", "hús", "noun", "food", "u05-l01"],
  ["fish", "hal", "noun", "food", "u05-l01"],
  ["vegetable", "zöldség", "noun", "food", "u05-l01", ["vegetable", "vegetables"]],
  ["fruit", "gyümölcs", "noun", "food", "u05-l01"],
  ["cake", "sütemény / torta", "noun", "food", "u05-l02"],
  ["breakfast", "reggeli", "noun", "food", "u05-l01"],
  ["lunch", "ebéd", "noun", "food", "u05-l01"],
  ["dinner", "vacsora", "noun", "food", "u05-l01"],
  ["cook", "főzni", "verb", "food", "u05-l02", ["cook", "cooks", "cooked"]],
  ["make", "csinálni / készíteni", "verb", "food", "u05-l02", ["make", "makes", "made"]],
  ["buy", "venni / vásárolni", "verb", "shopping", "u05-l02", ["buy", "buys", "bought"]],
  ["like", "szeretni / kedvelni", "verb", "opinions", "u05-l01", ["like", "likes", "liked"]],
  ["want", "akarni", "verb", "opinions", "u05-l02", ["want", "wants", "wanted"]],
  ["shop", "bolt / vásárolni", "noun", "shopping", "u05-l02", ["shop", "shops"]],
  ["price", "ár", "noun", "shopping", "u05-l02", ["price", "prices"]],
  ["money", "pénz", "noun", "shopping", "u05-l02"],
  ["some", "néhány / egy kis", "determiner", "food", "u05-l01"],
  ["any", "bármennyi / semennyi", "determiner", "food", "u05-l01"],
  ["much", "sok (megszámlálhatatlan)", "determiner", "food", "u05-l02"],
  ["many", "sok (megszámlálható)", "determiner", "food", "u05-l02"],

  // ---- Unit 6: time, weather, plans ----
  ["time", "idő", "noun", "time", "u06-l01"],
  ["hour", "óra (időtartam)", "noun", "time", "u06-l01", ["hour", "hours"]],
  ["minute", "perc", "noun", "time", "u06-l01", ["minute", "minutes"]],
  ["today", "ma", "noun", "time", "u06-l01"],
  ["tomorrow", "holnap", "noun", "time", "u06-l01"],
  ["yesterday", "tegnap", "noun", "past", "u06-l01"],
  ["week", "hét", "noun", "time", "u06-l01", ["week", "weeks"]],
  ["month", "hónap", "noun", "time", "u06-l01", ["month", "months"]],
  ["year", "év", "noun", "time", "u06-l01", ["year", "years"]],
  ["Monday", "hétfő", "noun", "time", "u06-l01"],
  ["Tuesday", "kedd", "noun", "time", "u06-l01"],
  ["Wednesday", "szerda", "noun", "time", "u06-l01"],
  ["Thursday", "csütörtök", "noun", "time", "u06-l01"],
  ["Friday", "péntek", "noun", "time", "u06-l01"],
  ["Saturday", "szombat", "noun", "time", "u06-l01"],
  ["Sunday", "vasárnap", "noun", "time", "u06-l01"],
  ["weekend", "hétvége", "noun", "time", "u06-l02"],
  ["weather", "időjárás", "noun", "weather", "u06-l02"],
  ["sunny", "napos", "adjective", "weather", "u06-l02"],
  ["rainy", "esős", "adjective", "weather", "u06-l02"],
  ["cold", "hideg", "adjective", "weather", "u06-l02"],
  ["hot", "meleg / forró", "adjective", "weather", "u06-l02"],
  ["warm", "meleg (kellemes)", "adjective", "weather", "u06-l02"],
  ["plan", "terv / tervezni", "noun", "plans", "u06-l02", ["plan", "plans", "planned"]],
  ["meet", "találkozni", "verb", "plans", "u06-l02", ["meet", "meets", "met"]],
  ["can", "tud / -hat", "verb", "plans", "u06-l02", ["can", "could"]],
  ["going to", "fog (jövő idő)", "phrase", "plans", "u06-l02"],
  ["free", "szabad (ráér)", "adjective", "plans", "u06-l02"],
  ["busy", "elfoglalt", "adjective", "plans", "u06-l02"],

  // ---- Unit 7: phone & video calls ----
  ["call", "hívni / hívás", "verb", "phone", "u07-l01", ["call", "calls", "called"]],
  ["phone", "telefon", "noun", "phone", "u07-l01", ["phone", "phones"]],
  ["hear", "hallani", "verb", "phone", "u07-l01", ["hear", "hears", "heard"]],
  ["see", "látni", "verb", "phone", "u07-l01", ["see", "sees", "saw"]],
  ["repeat", "megismételni", "verb", "conversation", "u07-l01", ["repeat", "repeats", "repeated"]],
  ["slowly", "lassan", "adverb", "conversation", "u07-l01"],
  ["again", "újra", "adverb", "conversation", "u07-l01"],
  ["understand", "érteni", "verb", "conversation", "u07-l01", ["understand", "understands", "understood"]],
  ["wait", "várni", "verb", "conversation", "u07-l01", ["wait", "waits", "waited"]],
  ["moment", "pillanat", "noun", "conversation", "u07-l01"],
  ["me", "engem / nekem", "pronoun", "conversation", "u07-l02"],
  ["him", "őt (férfi)", "pronoun", "conversation", "u07-l02"],
  ["them", "őket", "pronoun", "conversation", "u07-l02"],

  // ---- Unit 8: hobbies, opinions ----
  ["hobby", "hobbi", "noun", "hobbies", "u08-l01", ["hobby", "hobbies"]],
  ["music", "zene", "noun", "hobbies", "u08-l01"],
  ["book", "könyv", "noun", "hobbies", "u08-l01", ["book", "books"]],
  ["film", "film", "noun", "hobbies", "u08-l01", ["film", "films"]],
  ["sport", "sport", "noun", "hobbies", "u08-l01", ["sport", "sports"]],
  ["garden", "kertészkedés", "noun", "hobbies", "u08-l01"],
  ["swim", "úszni", "verb", "hobbies", "u08-l01", ["swim", "swims", "swam"]],
  ["dance", "táncolni", "verb", "hobbies", "u08-l01", ["dance", "dances", "danced"]],
  ["sing", "énekelni", "verb", "hobbies", "u08-l01", ["sing", "sings", "sang"]],
  ["play", "játszani", "verb", "hobbies", "u08-l01", ["play", "plays", "played"]],
  ["love", "szeretni (nagyon)", "verb", "opinions", "u08-l01", ["love", "loves", "loved"]],
  ["enjoy", "élvezni", "verb", "opinions", "u08-l01", ["enjoy", "enjoys", "enjoyed"]],
  ["favourite", "kedvenc", "adjective", "opinions", "u08-l02"],
  ["interesting", "érdekes", "adjective", "opinions", "u08-l02"],
  ["boring", "unalmas", "adjective", "opinions", "u08-l02"],
  ["beautiful", "gyönyörű", "adjective", "opinions", "u08-l02"],
  ["horse", "ló", "noun", "hobbies", "u08-l02", ["horse", "horses"]],
  ["think", "gondolni", "verb", "opinions", "u08-l02", ["think", "thinks", "thought"]],

  // ---- Unit 9: town, transport ----
  ["street", "utca", "noun", "town", "u09-l01", ["street", "streets"]],
  ["station", "állomás / megálló", "noun", "transport", "u09-l01", ["station", "stations"]],
  ["bus", "busz", "noun", "transport", "u09-l01", ["bus", "buses"]],
  ["train", "vonat", "noun", "transport", "u09-l01", ["train", "trains"]],
  ["car", "autó", "noun", "transport", "u09-l01", ["car", "cars"]],
  ["taxi", "taxi", "noun", "transport", "u09-l01"],
  ["ticket", "jegy", "noun", "transport", "u09-l02", ["ticket", "tickets"]],
  ["platform", "vágány / peron", "noun", "transport", "u09-l02", ["platform", "platforms"]],
  ["left", "bal", "noun", "town", "u09-l01"],
  ["right", "jobb", "noun", "town", "u09-l01"],
  ["straight", "egyenesen", "adverb", "town", "u09-l01"],
  ["near", "közel", "adjective", "town", "u09-l01"],
  ["far", "messze", "adjective", "town", "u09-l01"],
  ["first", "először", "adverb", "town", "u09-l01"],
  ["then", "aztán", "adverb", "town", "u09-l01"],
  ["turn", "fordulni", "verb", "town", "u09-l01", ["turn", "turns", "turned"]],

  // ---- Unit 10: restaurant, hotel, services ----
  ["restaurant", "étterem", "noun", "services", "u10-l01", ["restaurant", "restaurants"]],
  ["hotel", "szálloda / hotel", "noun", "hotel", "u10-l02", ["hotel", "hotels"]],
  ["menu", "étlap", "noun", "services", "u10-l01", ["menu", "menus"]],
  ["table", "asztal", "noun", "services", "u10-l01", ["table", "tables"]],
  ["bill", "számla", "noun", "services", "u10-l01"],
  ["order", "rendelni", "verb", "services", "u10-l01", ["order", "orders", "ordered"]],
  ["room", "szoba (hotel)", "noun", "hotel", "u10-l02"],
  ["key", "kulcs", "noun", "hotel", "u10-l02", ["key", "keys"]],
  ["night", "éjszaka (hotel)", "noun", "hotel", "u10-l02"],
  ["book", "foglalni", "verb", "hotel", "u10-l02", ["book", "books", "booked"]],
  ["help", "segíteni / segítség", "verb", "services", "u10-l01", ["help", "helps", "helped"]],
  ["problem", "probléma / gond", "noun", "services", "u10-l02", ["problem", "problems"]],
  ["excuse me", "elnézést", "phrase", "services", "u10-l01"],

  // ---- Unit 11: online teaching, technology ----
  ["lesson", "óra / lecke", "noun", "teaching", "u11-l01", ["lesson", "lessons"]],
  ["camera", "kamera", "noun", "technology", "u11-l01", ["camera", "cameras"]],
  ["microphone", "mikrofon", "noun", "technology", "u11-l01", ["microphone", "microphones"]],
  ["screen", "képernyő", "noun", "technology", "u11-l01", ["screen", "screens"]],
  ["computer", "számítógép", "noun", "technology", "u11-l01", ["computer", "computers"]],
  ["internet", "internet", "noun", "technology", "u11-l01"],
  ["start", "kezdeni / indítani", "verb", "teaching", "u11-l01", ["start", "starts", "started"]],
  ["turn on", "bekapcsolni", "verb", "technology", "u11-l01", ["turn on", "turns on", "turned on"]],
  ["turn off", "kikapcsolni", "verb", "technology", "u11-l01", ["turn off", "turns off", "turned off"]],
  ["click", "kattintani", "verb", "technology", "u11-l02", ["click", "clicks", "clicked"]],
  ["ready", "kész", "adjective", "teaching", "u11-l01"],
  ["excellent", "kiváló", "adjective", "teaching", "u11-l01"],
  ["student", "diák / tanuló", "noun", "teaching", "u11-l01", ["student", "students"]],

  // ---- Unit 12: past ----
  ["was", "voltam / volt", "verb", "past", "u12-l01", ["was", "were"]],
  ["went", "ment (megy múlt)", "verb", "past", "u12-l01"],
  ["saw", "látott (lát múlt)", "verb", "past", "u12-l01"],
  ["visit", "meglátogatni", "verb", "past", "u12-l01", ["visit", "visits", "visited"]],
  ["yesterday", "tegnap", "noun", "past", "u12-l01"],
  ["last week", "múlt héten", "phrase", "past", "u12-l01"],
  ["ago", "ezelőtt", "adverb", "past", "u12-l02"],
  ["holiday", "nyaralás / szabadság", "noun", "travel", "u12-l02", ["holiday", "holidays"]],

  // ---- Unit 13: travel plans ----
  ["travel", "utazni / utazás", "verb", "travel", "u13-l01", ["travel", "travels", "travelled"]],
  ["trip", "kirándulás / út", "noun", "travel", "u13-l01", ["trip", "trips"]],
  ["visit", "látogatás", "noun", "travel", "u13-l01"],
  ["luggage", "poggyász", "noun", "travel", "u13-l02"],
  ["suitcase", "bőrönd", "noun", "travel", "u13-l02", ["suitcase", "suitcases"]],
  ["passport", "útlevél", "noun", "travel", "u13-l02", ["passport", "passports"]],
  ["need", "kell / szüksége van", "verb", "travel", "u13-l01", ["need", "needs", "needed"]],
  ["bring", "hozni", "verb", "travel", "u13-l02", ["bring", "brings", "brought"]],

  // ---- Unit 14: airport ----
  ["airport", "reptér", "noun", "airport", "u14-l01", ["airport", "airports"]],
  ["flight", "járat / repülés", "noun", "airport", "u14-l01", ["flight", "flights"]],
  ["gate", "kapu (reptér)", "noun", "airport", "u14-l01", ["gate", "gates"]],
  ["check-in", "check-in / becsekkolás", "noun", "airport", "u14-l01"],
  ["security", "biztonsági ellenőrzés", "noun", "airport", "u14-l01"],
  ["boarding", "beszállás", "noun", "airport", "u14-l02"],
  ["seat", "ülés / hely", "noun", "airport", "u14-l02", ["seat", "seats"]],
  ["late", "késő / késésben", "adjective", "airport", "u14-l02"],
  ["desk", "pult", "noun", "airport", "u14-l01", ["desk", "desks"]],

  // ---- Unit 15: on the plane, feelings ----
  ["plane", "repülő", "noun", "flying", "u15-l01", ["plane", "planes"]],
  ["afraid", "fél (vmitől)", "adjective", "feelings", "u15-l01"],
  ["nervous", "ideges", "adjective", "feelings", "u15-l01"],
  ["scared", "megijedt / fél", "adjective", "feelings", "u15-l01"],
  ["calm", "nyugodt", "adjective", "feelings", "u15-l01"],
  ["blanket", "takaró", "noun", "flying", "u15-l01", ["blanket", "blankets"]],
  ["toilet", "mosdó / wc", "noun", "flying", "u15-l01"],
  ["land", "landolni / leszállni", "verb", "flying", "u15-l02", ["land", "lands", "landed"]],
  ["safe", "biztonságos", "adjective", "feelings", "u15-l01"],
  ["okay", "rendben / oké", "adjective", "feelings", "u15-l01"],

  // ---- Unit 16 + spiral: feelings, extra ----
  ["tired", "fáradt", "adjective", "feelings", "u16-l01"],
  ["glad", "örül", "adjective", "feelings", "u16-l01"],
  ["welcome", "szívesen / üdvözöllek", "phrase", "greetings", "u16-l01"],
  ["together", "együtt", "adverb", "family", "u16-l01"],

  // ---- Numbers ----
  ["one", "egy", "number", "numbers", "u01-l02"],
  ["two", "kettő", "number", "numbers", "u01-l02"],
  ["three", "három", "number", "numbers", "u01-l02"],
  ["four", "négy", "number", "numbers", "u01-l02"],
  ["five", "öt", "number", "numbers", "u01-l02"],
  ["six", "hat", "number", "numbers", "u01-l02"],
  ["seven", "hét (szám)", "number", "numbers", "u01-l02"],
  ["eight", "nyolc", "number", "numbers", "u01-l02"],
  ["nine", "kilenc", "number", "numbers", "u01-l02"],
  ["ten", "tíz", "number", "numbers", "u01-l02"],
  ["eleven", "tizenegy", "number", "numbers", "u06-l01"],
  ["twelve", "tizenkettő", "number", "numbers", "u06-l01"],
  ["twenty", "húsz", "number", "numbers", "u06-l01"],
  ["thirty", "harminc", "number", "numbers", "u06-l01"],
  ["hundred", "száz", "number", "numbers", "u06-l01"],

  // ---- Colours (receptive-adjacent productive) ----
  ["red", "piros", "adjective", "colours", "u08-l02"],
  ["blue", "kék", "adjective", "colours", "u08-l02"],
  ["green", "zöld", "adjective", "colours", "u08-l02"],
  ["white", "fehér", "adjective", "colours", "u08-l02"],
  ["black", "fekete", "adjective", "colours", "u08-l02"],
];

// Receptive items — understood, not required productively.
export const RECEPTIVE = [
  ["announcement", "bejelentés", "noun", "airport"],
  ["passenger", "utas", "noun", "airport"],
  ["departure", "indulás", "noun", "airport"],
  ["arrival", "érkezés", "noun", "airport"],
  ["delay", "késés", "noun", "airport"],
  ["cancelled", "törölve", "adjective", "airport"],
  ["fasten", "becsatolni", "verb", "flying"],
  ["seatbelt", "biztonsági öv", "noun", "flying"],
  ["crew", "személyzet", "noun", "flying"],
  ["captain", "kapitány", "noun", "flying"],
  ["runway", "kifutópálya", "noun", "flying"],
  ["turbulence", "turbulencia", "noun", "flying"],
  ["reception", "recepció", "noun", "hotel"],
  ["reservation", "foglalás", "noun", "hotel"],
  ["breakfast included", "reggeli az árban", "phrase", "hotel"],
  ["floor", "emelet", "noun", "hotel"],
  ["lift", "lift", "noun", "hotel"],
  ["waiter", "pincér", "noun", "services"],
  ["starter", "előétel", "noun", "services"],
  ["dessert", "desszert", "noun", "services"],
  ["change", "visszajáró", "noun", "shopping"],
  ["receipt", "nyugta", "noun", "shopping"],
  ["timetable", "menetrend", "noun", "transport"],
  ["direction", "irány", "noun", "town"],
  ["corner", "sarok", "noun", "town"],
  ["opposite", "szemben", "preposition", "town"],
  ["between", "között", "preposition", "town"],
  ["neighbour", "szomszéd", "noun", "home"],
  ["upstairs", "emeleten", "adverb", "home"],
  ["downstairs", "földszinten", "adverb", "home"],
  ["recipe", "recept", "noun", "food"],
  ["delicious", "finom", "adjective", "food"],
  ["healthy", "egészséges", "adjective", "food"],
  ["dessert", "desszert", "noun", "food"],
  ["celebrate", "ünnepelni", "verb", "family"],
  ["celebration", "ünneplés", "noun", "family"],
  ["birthday", "születésnap", "noun", "family"],
  ["Christmas", "karácsony", "noun", "family"],
  ["wedding", "esküvő", "noun", "family"],
  ["retirement", "nyugdíj", "noun", "family"],
  ["colleague", "kolléga", "noun", "daily-life"],
  ["meeting", "megbeszélés / meeting", "noun", "travel"],
  ["experience", "tapasztalat / élmény", "noun", "travel"],
  ["abroad", "külföldön", "adverb", "travel"],
  ["rowing", "evezés", "noun", "hobbies"],
  ["competition", "verseny", "noun", "hobbies"],
  ["training", "edzés", "noun", "hobbies"],
  ["university", "egyetem", "noun", "hobbies"],
  ["programming", "programozás", "noun", "technology"],
  ["company", "cég", "noun", "technology"],
  ["author", "szerző", "noun", "hobbies"],
  ["recommend", "ajánlani", "verb", "opinions"],
  ["connection", "kapcsolat (internet)", "noun", "technology"],
  ["nervous flyer", "félős utas", "phrase", "flying"],
  ["breathe", "lélegezni", "verb", "feelings"],
  ["relax", "ellazulni", "verb", "feelings"],
  ["worried", "aggódó", "adjective", "feelings"],
  ["comfortable", "kényelmes", "adjective", "feelings"],
  ["message", "üzenet", "noun", "phone"],
  ["voice message", "hangüzenet", "phrase", "phone"],
  ["online", "online / interneten", "adjective", "technology"],
  ["download", "letölteni", "verb", "technology"],
  ["password", "jelszó", "noun", "technology"],
];
