// Phase 2 vocabulary expansion — EVP (English Vocabulary Profile) A1-anchored core,
// prioritised by general frequency, extending Marta's course toward ~700 productive words.
// A2 "beginnings" are flagged with a 7th element "A2" (kept internal; never labelled to Marta).
// Duplicate headwords already present in lexicon-source.mjs are skipped by the generator.
// Format: [headword, hu, partOfSpeech, theme, firstLesson, acceptedForms?, level?]

export const EXTRA = [
  // ===== Numbers & ordinals =====
  ["zero", "nulla", "number", "numbers", "u06-l01"],
  ["thirteen", "tizenhárom", "number", "numbers", "u06-l01"],
  ["fourteen", "tizennégy", "number", "numbers", "u06-l01"],
  ["fifteen", "tizenöt", "number", "numbers", "u06-l01"],
  ["sixteen", "tizenhat", "number", "numbers", "u06-l01"],
  ["seventeen", "tizenhét", "number", "numbers", "u06-l01"],
  ["eighteen", "tizennyolc", "number", "numbers", "u06-l01"],
  ["nineteen", "tizenkilenc", "number", "numbers", "u06-l01"],
  ["forty", "negyven", "number", "numbers", "u06-l01"],
  ["fifty", "ötven", "number", "numbers", "u06-l01"],
  ["sixty", "hatvan", "number", "numbers", "u06-l01"],
  ["seventy", "hetven", "number", "numbers", "u06-l01"],
  ["eighty", "nyolcvan", "number", "numbers", "u06-l01"],
  ["ninety", "kilencven", "number", "numbers", "u06-l01"],
  ["thousand", "ezer", "number", "numbers", "u06-l01"],
  ["first", "első", "adjective", "numbers", "u09-l01"],
  ["second", "második", "adjective", "numbers", "u09-l01", null, "A2"],
  ["third", "harmadik", "adjective", "numbers", "u09-l01", null, "A2"],
  ["number", "szám", "noun", "numbers", "u06-l01", ["number", "numbers"]],

  // ===== Time & months =====
  ["o'clock", "óra (pontos idő)", "adverb", "time", "u06-l01"],
  ["half", "fél", "noun", "time", "u06-l01"],
  ["quarter", "negyed", "noun", "time", "u06-l01", null, "A2"],
  ["early", "korán", "adverb", "time", "u06-l01"],
  ["now", "most", "adverb", "time", "u06-l01"],
  ["soon", "hamarosan", "adverb", "time", "u06-l01"],
  ["before", "előtt", "preposition", "time", "u06-l01"],
  ["after", "után", "preposition", "time", "u06-l01"],
  ["date", "dátum", "noun", "time", "u06-l01", ["date", "dates"]],
  ["January", "január", "noun", "time", "u06-l01"],
  ["February", "február", "noun", "time", "u06-l01"],
  ["March", "március", "noun", "time", "u06-l01"],
  ["April", "április", "noun", "time", "u06-l01"],
  ["May", "május", "noun", "time", "u06-l01"],
  ["June", "június", "noun", "time", "u06-l01"],
  ["July", "július", "noun", "time", "u06-l01"],
  ["August", "augusztus", "noun", "time", "u06-l01"],
  ["September", "szeptember", "noun", "time", "u06-l01"],
  ["October", "október", "noun", "time", "u06-l01"],
  ["November", "november", "noun", "time", "u06-l01"],
  ["December", "december", "noun", "time", "u06-l01"],

  // ===== The body =====
  ["body", "test", "noun", "body", "u04-l02"],
  ["head", "fej", "noun", "body", "u04-l02", ["head", "heads"]],
  ["face", "arc", "noun", "body", "u04-l02", ["face", "faces"]],
  ["eye", "szem", "noun", "body", "u04-l02", ["eye", "eyes"]],
  ["ear", "fül", "noun", "body", "u04-l02", ["ear", "ears"]],
  ["nose", "orr", "noun", "body", "u04-l02", ["nose", "noses"]],
  ["mouth", "száj", "noun", "body", "u04-l02", ["mouth", "mouths"]],
  ["hair", "haj", "noun", "body", "u04-l02"],
  ["hand", "kéz", "noun", "body", "u04-l02", ["hand", "hands"]],
  ["arm", "kar", "noun", "body", "u04-l02", ["arm", "arms"]],
  ["leg", "láb (comb)", "noun", "body", "u04-l02", ["leg", "legs"]],
  ["foot", "lábfej", "noun", "body", "u04-l02", ["foot", "feet"]],
  ["tooth", "fog", "noun", "body", "u04-l02", ["tooth", "teeth"]],

  // ===== Health =====
  ["doctor", "orvos", "noun", "health", "u10-l02", ["doctor", "doctors"]],
  ["nurse", "nővér (ápoló)", "noun", "health", "u10-l02", ["nurse", "nurses"]],
  ["hospital", "kórház", "noun", "health", "u10-l02", ["hospital", "hospitals"]],
  ["medicine", "gyógyszer", "noun", "health", "u10-l02", null, "A2"],
  ["ill", "beteg", "adjective", "health", "u10-l02"],
  ["sick", "beteg / rosszul", "adjective", "health", "u10-l02"],
  ["pain", "fájdalom", "noun", "health", "u10-l02", null, "A2"],
  ["better", "jobban / jobb", "adjective", "health", "u10-l02"],
  ["rest", "pihenés / pihenni", "noun", "health", "u10-l02", ["rest", "rests", "rested"]],
  ["hurt", "fájni", "verb", "health", "u10-l02", ["hurt", "hurts"], "A2"],

  // ===== Clothes =====
  ["clothes", "ruhák", "noun", "clothes", "u13-l02"],
  ["shirt", "ing", "noun", "clothes", "u13-l02", ["shirt", "shirts"]],
  ["trousers", "nadrág", "noun", "clothes", "u13-l02"],
  ["dress", "ruha (női)", "noun", "clothes", "u13-l02", ["dress", "dresses"]],
  ["shoes", "cipő", "noun", "clothes", "u13-l02"],
  ["coat", "kabát", "noun", "clothes", "u13-l02", ["coat", "coats"]],
  ["hat", "kalap / sapka", "noun", "clothes", "u13-l02", ["hat", "hats"]],
  ["jacket", "dzseki", "noun", "clothes", "u13-l02", ["jacket", "jackets"]],
  ["wear", "viselni", "verb", "clothes", "u13-l02", ["wear", "wears", "wore"], "A2"],

  // ===== Home & furniture =====
  ["window", "ablak", "noun", "home", "u04-l02", ["window", "windows"]],
  ["door", "ajtó", "noun", "home", "u04-l02", ["door", "doors"]],
  ["chair", "szék", "noun", "home", "u04-l02", ["chair", "chairs"]],
  ["bed", "ágy", "noun", "home", "u04-l02", ["bed", "beds"]],
  ["sofa", "kanapé", "noun", "home", "u04-l02", ["sofa", "sofas"]],
  ["wall", "fal", "noun", "home", "u04-l02", ["wall", "walls"]],
  ["floor", "padló / emelet", "noun", "home", "u04-l02", ["floor", "floors"]],
  ["bathroom", "fürdőszoba", "noun", "home", "u04-l02", ["bathroom", "bathrooms"]],
  ["bedroom", "hálószoba", "noun", "home", "u04-l02", ["bedroom", "bedrooms"]],
  ["television", "televízió", "noun", "home", "u04-l02", ["television", "televisions"]],
  ["fridge", "hűtő", "noun", "home", "u04-l02", ["fridge", "fridges"]],
  ["lamp", "lámpa", "noun", "home", "u04-l02", ["lamp", "lamps"]],
  ["flat", "lakás", "noun", "home", "u04-l02", ["flat", "flats"]],

  // ===== Food & drink =====
  ["rice", "rizs", "noun", "food", "u05-l01"],
  ["potato", "burgonya", "noun", "food", "u05-l01", ["potato", "potatoes"]],
  ["tomato", "paradicsom", "noun", "food", "u05-l01", ["tomato", "tomatoes"]],
  ["onion", "hagyma", "noun", "food", "u05-l01", ["onion", "onions"]],
  ["chicken", "csirke", "noun", "food", "u05-l01"],
  ["salad", "saláta", "noun", "food", "u05-l01", ["salad", "salads"]],
  ["sugar", "cukor", "noun", "food", "u05-l01"],
  ["salt", "só", "noun", "food", "u05-l01"],
  ["butter", "vaj", "noun", "food", "u05-l01"],
  ["chocolate", "csokoládé", "noun", "food", "u05-l01"],
  ["orange", "narancs", "noun", "food", "u05-l01", ["orange", "oranges"]],
  ["banana", "banán", "noun", "food", "u05-l01", ["banana", "bananas"]],
  ["sandwich", "szendvics", "noun", "food", "u05-l01", ["sandwich", "sandwiches"]],
  ["juice", "gyümölcslé", "noun", "food", "u05-l01"],
  ["wine", "bor", "noun", "food", "u05-l02", null, "A2"],
  ["dessert", "desszert", "noun", "food", "u05-l02", null, "A2"],
  ["hungry", "éhes", "adjective", "food", "u05-l01"],
  ["thirsty", "szomjas", "adjective", "food", "u05-l01"],
  ["delicious", "finom", "adjective", "food", "u05-l02", null, "A2"],
  ["taste", "íz / ízlelni", "verb", "food", "u05-l02", ["taste", "tastes", "tasted"], "A2"],

  // ===== Town & places =====
  ["town", "kisváros", "noun", "town", "u09-l01", ["town", "towns"]],
  ["village", "falu", "noun", "town", "u09-l01", ["village", "villages"]],
  ["road", "út", "noun", "town", "u09-l01", ["road", "roads"]],
  ["bank", "bank", "noun", "town", "u09-l01", ["bank", "banks"]],
  ["park", "park", "noun", "town", "u09-l01", ["park", "parks"]],
  ["church", "templom", "noun", "town", "u09-l01", ["church", "churches"]],
  ["school", "iskola", "noun", "town", "u09-l01", ["school", "schools"]],
  ["market", "piac", "noun", "town", "u09-l01", ["market", "markets"]],
  ["supermarket", "szupermarket", "noun", "town", "u09-l01", ["supermarket", "supermarkets"]],
  ["cinema", "mozi", "noun", "town", "u09-l01", ["cinema", "cinemas"]],
  ["museum", "múzeum", "noun", "town", "u09-l01", ["museum", "museums"]],
  ["square", "tér", "noun", "town", "u09-l01", ["square", "squares"], "A2"],
  ["bridge", "híd", "noun", "town", "u09-l01", ["bridge", "bridges"], "A2"],
  ["library", "könyvtár", "noun", "town", "u09-l01", ["library", "libraries"]],
  ["pharmacy", "gyógyszertár", "noun", "town", "u10-l02", ["pharmacy", "pharmacies"], "A2"],
  ["centre", "központ", "noun", "town", "u09-l01", ["centre", "centres"]],
  ["place", "hely", "noun", "town", "u09-l01", ["place", "places"]],
  ["corner", "sarok", "noun", "town", "u09-l01", ["corner", "corners"]],

  // ===== Nature & weather =====
  ["tree", "fa", "noun", "weather", "u06-l02", ["tree", "trees"]],
  ["flower", "virág", "noun", "weather", "u06-l02", ["flower", "flowers"]],
  ["sea", "tenger", "noun", "weather", "u06-l02", ["sea", "seas"]],
  ["river", "folyó", "noun", "weather", "u06-l02", ["river", "rivers"]],
  ["lake", "tó", "noun", "weather", "u06-l02", ["lake", "lakes"]],
  ["mountain", "hegy", "noun", "weather", "u06-l02", ["mountain", "mountains"]],
  ["beach", "strand / tengerpart", "noun", "weather", "u06-l02", ["beach", "beaches"]],
  ["sky", "ég", "noun", "weather", "u06-l02"],
  ["sun", "nap (égitest)", "noun", "weather", "u06-l02"],
  ["rain", "eső", "noun", "weather", "u06-l02"],
  ["snow", "hó", "noun", "weather", "u06-l02"],
  ["wind", "szél", "noun", "weather", "u06-l02"],
  ["cloud", "felhő", "noun", "weather", "u06-l02", ["cloud", "clouds"]],
  ["cloudy", "felhős", "adjective", "weather", "u06-l02"],
  ["windy", "szeles", "adjective", "weather", "u06-l02"],
  ["wet", "nedves / esős", "adjective", "weather", "u06-l02"],
  ["dry", "száraz", "adjective", "weather", "u06-l02"],

  // ===== Animals =====
  ["animal", "állat", "noun", "hobbies", "u08-l02", ["animal", "animals"]],
  ["dog", "kutya", "noun", "hobbies", "u08-l02", ["dog", "dogs"]],
  ["cat", "macska", "noun", "hobbies", "u08-l02", ["cat", "cats"]],
  ["bird", "madár", "noun", "hobbies", "u08-l02", ["bird", "birds"]],
  ["cow", "tehén", "noun", "hobbies", "u08-l02", ["cow", "cows"]],

  // ===== Jobs =====
  ["job", "állás / munka", "noun", "identity", "u03-l02", ["job", "jobs"]],
  ["driver", "sofőr", "noun", "identity", "u03-l02", ["driver", "drivers"]],
  ["engineer", "mérnök", "noun", "identity", "u03-l02", ["engineer", "engineers"], "A2"],
  ["manager", "vezető / menedzser", "noun", "identity", "u03-l02", ["manager", "managers"], "A2"],
  ["artist", "művész", "noun", "identity", "u03-l02", ["artist", "artists"], "A2"],
  ["nurse", "ápoló", "noun", "identity", "u03-l02", null],

  // ===== Family (more) =====
  ["baby", "baba", "noun", "family", "u02-l01", ["baby", "babies"]],
  ["cousin", "unokatestvér", "noun", "family", "u02-l01", ["cousin", "cousins"]],
  ["grandparents", "nagyszülők", "noun", "family", "u02-l01"],
  ["people", "emberek", "noun", "family", "u02-l01"],
  ["man", "férfi", "noun", "family", "u02-l01", ["man", "men"]],
  ["woman", "nő", "noun", "family", "u02-l01", ["woman", "women"]],
  ["girl", "lány", "noun", "family", "u02-l01", ["girl", "girls"]],
  ["boy", "fiú", "noun", "family", "u02-l01", ["boy", "boys"]],
  ["person", "személy", "noun", "family", "u02-l01", ["person", "people"]],

  // ===== Common verbs (A1 high-frequency) =====
  ["open", "kinyitni", "verb", "daily-life", "u09-l01", ["open", "opens", "opened"]],
  ["close", "becsukni", "verb", "daily-life", "u09-l01", ["close", "closes", "closed"]],
  ["stop", "megállni / abbahagyni", "verb", "town", "u09-l01", ["stop", "stops", "stopped"]],
  ["give", "adni", "verb", "daily-life", "u05-l02", ["give", "gives", "gave"]],
  ["take", "venni / vinni", "verb", "daily-life", "u09-l01", ["take", "takes", "took"]],
  ["put", "tenni", "verb", "daily-life", "u04-l01", ["put", "puts"]],
  ["get", "kapni / szerezni", "verb", "daily-life", "u04-l01", ["get", "gets", "got"]],
  ["find", "megtalálni", "verb", "town", "u09-l01", ["find", "finds", "found"]],
  ["know", "tudni / ismerni", "verb", "conversation", "u07-l02", ["know", "knows", "knew"]],
  ["ask", "kérdezni", "verb", "conversation", "u07-l02", ["ask", "asks", "asked"]],
  ["answer", "válaszolni", "verb", "conversation", "u07-l02", ["answer", "answers", "answered"]],
  ["tell", "mondani (vkinek)", "verb", "conversation", "u07-l02", ["tell", "tells", "told"]],
  ["say", "mondani", "verb", "conversation", "u07-l02", ["say", "says", "said"]],
  ["show", "megmutatni", "verb", "daily-life", "u09-l01", ["show", "shows", "showed"]],
  ["use", "használni", "verb", "technology", "u11-l02", ["use", "uses", "used"]],
  ["pay", "fizetni", "verb", "shopping", "u05-l02", ["pay", "pays", "paid"]],
  ["send", "küldeni", "verb", "phone", "u07-l02", ["send", "sends", "sent"]],
  ["carry", "cipelni / vinni", "verb", "travel", "u13-l02", ["carry", "carries", "carried"], "A2"],
  ["wash", "mosni / mosakodni", "verb", "daily-life", "u04-l01", ["wash", "washes", "washed"]],
  ["clean", "takarítani / tiszta", "verb", "daily-life", "u04-l01", ["clean", "cleans", "cleaned"]],
  ["stay", "maradni", "verb", "travel", "u13-l01", ["stay", "stays", "stayed"]],
  ["leave", "elmenni / elhagyni", "verb", "travel", "u13-l01", ["leave", "leaves", "left"], "A2"],
  ["arrive", "megérkezni", "verb", "travel", "u13-l01", ["arrive", "arrives", "arrived"], "A2"],
  ["drive", "vezetni (autót)", "verb", "transport", "u09-l02", ["drive", "drives", "drove"]],
  ["fly", "repülni", "verb", "flying", "u15-l01", ["fly", "flies", "flew"]],
  ["run", "futni", "verb", "hobbies", "u08-l01", ["run", "runs", "ran"]],
  ["sit", "ülni", "verb", "daily-life", "u04-l01", ["sit", "sits", "sat"]],
  ["stand", "állni", "verb", "daily-life", "u04-l01", ["stand", "stands", "stood"]],
  ["look", "nézni", "verb", "daily-life", "u04-l02", ["look", "looks", "looked"]],
  ["listen", "hallgatni", "verb", "hobbies", "u08-l01", ["listen", "listens", "listened"]],
  ["write", "írni", "verb", "teaching", "u11-l01", ["write", "writes", "wrote"]],
  ["learn", "tanulni", "verb", "teaching", "u11-l01", ["learn", "learns", "learned"]],
  ["teach", "tanítani", "verb", "teaching", "u11-l01", ["teach", "teaches", "taught"]],
  ["remember", "emlékezni", "verb", "conversation", "u12-l02", ["remember", "remembers", "remembered"], "A2"],
  ["feel", "érezni", "verb", "feelings", "u15-l01", ["feel", "feels", "felt"]],
  ["hope", "remélni", "verb", "conversation", "u16-l01", ["hope", "hopes", "hoped"], "A2"],
  ["try", "megpróbálni", "verb", "conversation", "u12-l02", ["try", "tries", "tried"]],
  ["begin", "elkezdeni", "verb", "teaching", "u11-l01", ["begin", "begins", "began"], "A2"],
  ["finish", "befejezni", "verb", "teaching", "u11-l01", ["finish", "finishes", "finished"]],
  ["change", "változtatni / átszállni", "verb", "transport", "u09-l02", ["change", "changes", "changed"], "A2"],
  ["sell", "eladni", "verb", "shopping", "u05-l02", ["sell", "sells", "sold"], "A2"],

  // ===== Adjectives (A1) =====
  ["big", "nagy", "adjective", "opinions", "u03-l02"],
  ["small", "kicsi", "adjective", "opinions", "u03-l02"],
  ["long", "hosszú", "adjective", "opinions", "u03-l02"],
  ["new", "új", "adjective", "opinions", "u03-l02"],
  ["bad", "rossz", "adjective", "opinions", "u03-l02"],
  ["sad", "szomorú", "adjective", "feelings", "u15-l01"],
  ["easy", "könnyű", "adjective", "opinions", "u08-l02"],
  ["difficult", "nehéz (bonyolult)", "adjective", "opinions", "u08-l02"],
  ["hard", "nehéz / kemény", "adjective", "opinions", "u08-l02"],
  ["fast", "gyors", "adjective", "transport", "u09-l02"],
  ["slow", "lassú", "adjective", "transport", "u09-l02"],
  ["high", "magas (tárgy)", "adjective", "town", "u09-l01"],
  ["clean", "tiszta", "adjective", "home", "u04-l02"],
  ["dirty", "piszkos", "adjective", "home", "u04-l02"],
  ["expensive", "drága", "adjective", "shopping", "u05-l02", null, "A2"],
  ["cheap", "olcsó", "adjective", "shopping", "u05-l02"],
  ["important", "fontos", "adjective", "opinions", "u08-l02", null, "A2"],
  ["different", "különböző / más", "adjective", "opinions", "u08-l02", null, "A2"],
  ["same", "ugyanaz", "adjective", "opinions", "u08-l02"],
  ["lovely", "kedves / bájos", "adjective", "opinions", "u08-l02"],
  ["friendly", "barátságos", "adjective", "identity", "u03-l02"],
  ["quiet", "csendes", "adjective", "opinions", "u08-l02"],
  ["loud", "hangos", "adjective", "opinions", "u08-l02"],
  ["dark", "sötét", "adjective", "opinions", "u06-l02"],
  ["light", "világos / könnyű", "adjective", "opinions", "u06-l02"],
  ["full", "tele", "adjective", "food", "u05-l02"],
  ["empty", "üres", "adjective", "food", "u05-l02"],
  ["wrong", "rossz / helytelen", "adjective", "conversation", "u07-l02"],
  ["ready", "kész", "adjective", "plans", "u06-l02"],
  ["strong", "erős", "adjective", "opinions", "u08-l02"],
  ["angry", "mérges", "adjective", "feelings", "u16-l01", null, "A2"],
  ["surprised", "meglepett", "adjective", "feelings", "u16-l01", null, "A2"],
  ["excited", "izgatott", "adjective", "feelings", "u16-l01", null, "A2"],
  ["yellow", "sárga", "adjective", "colours", "u08-l02"],
  ["brown", "barna", "adjective", "colours", "u08-l02"],
  ["grey", "szürke", "adjective", "colours", "u08-l02"],
  ["pink", "rózsaszín", "adjective", "colours", "u08-l02"],

  // ===== Function words / adverbs / prepositions =====
  ["here", "itt", "adverb", "town", "u09-l01"],
  ["there", "ott", "adverb", "town", "u09-l01"],
  ["too", "is / túl", "adverb", "conversation", "u08-l02"],
  ["also", "szintén", "adverb", "conversation", "u08-l02"],
  ["only", "csak", "adverb", "conversation", "u08-l02"],
  ["maybe", "talán", "adverb", "conversation", "u06-l02"],
  ["really", "tényleg", "adverb", "opinions", "u08-l02"],
  ["just", "épp / csak", "adverb", "conversation", "u07-l02", null, "A2"],
  ["about", "-ról / -ről / kb.", "preposition", "conversation", "u08-l02"],
  ["up", "fel", "adverb", "town", "u09-l01"],
  ["down", "le", "adverb", "town", "u09-l01"],
  ["out", "ki / kint", "adverb", "daily-life", "u04-l01"],
  ["with", "-val / -vel", "preposition", "conversation", "u02-l02"],
  ["for", "-nak / -ért", "preposition", "conversation", "u05-l02"],
  ["at", "-nál / -kor", "preposition", "time", "u06-l01"],
  ["to", "-hoz / -ba", "preposition", "town", "u09-l01"],
  ["of", "-nak a ...", "preposition", "conversation", "u07-l02"],
  ["by", "-val (közlekedés) / mellett", "preposition", "transport", "u09-l02"],
  ["over", "fölött / vége", "preposition", "town", "u09-l01", null, "A2"],
  ["behind", "mögött", "preposition", "town", "u09-l01"],

  // ===== Shopping & money =====
  ["cost", "kerülni (vmennyibe)", "verb", "shopping", "u05-l02", ["cost", "costs"]],
  ["euro", "euró", "noun", "shopping", "u05-l02", ["euro", "euros"]],
  ["card", "kártya", "noun", "shopping", "u05-l02", ["card", "cards"]],
  ["cash", "készpénz", "noun", "shopping", "u05-l02"],
  ["free", "ingyenes / szabad", "adjective", "shopping", "u05-l02"],

  // ===== Travel (more) =====
  ["bag", "táska", "noun", "travel", "u13-l02", ["bag", "bags"]],
  ["map", "térkép", "noun", "travel", "u09-l01", ["map", "maps"]],
  ["tourist", "turista", "noun", "travel", "u13-l01", ["tourist", "tourists"], "A2"],
  ["journey", "utazás / út", "noun", "travel", "u13-l01", ["journey", "journeys"], "A2"],
  ["guide", "idegenvezető / útmutató", "noun", "travel", "u13-l01", ["guide", "guides"], "A2"],
  ["welcome", "üdvözlünk", "phrase", "travel", "u10-l02"],

  // ===== Technology & school =====
  ["email", "e-mail", "noun", "technology", "u11-l02", ["email", "emails"]],
  ["video", "videó", "noun", "technology", "u07-l02", ["video", "videos"]],
  ["mobile", "mobil(telefon)", "noun", "technology", "u11-l02", ["mobile", "mobiles"]],
  ["app", "alkalmazás / app", "noun", "technology", "u11-l02", ["app", "apps"], "A2"],
  ["word", "szó", "noun", "teaching", "u11-l01", ["word", "words"]],
  ["question", "kérdés", "noun", "teaching", "u11-l01", ["question", "questions"]],
  ["pen", "toll", "noun", "teaching", "u11-l01", ["pen", "pens"]],
  ["pencil", "ceruza", "noun", "teaching", "u11-l01", ["pencil", "pencils"]],
  ["paper", "papír", "noun", "teaching", "u11-l01"],
  ["page", "oldal", "noun", "teaching", "u11-l01", ["page", "pages"]],
  ["classroom", "osztályterem", "noun", "teaching", "u11-l01", ["classroom", "classrooms"]],
  ["homework", "házi feladat", "noun", "teaching", "u11-l01", null, "A2"],

  // ===== Feelings & conversation (more) =====
  ["hello", "szia (üdvözlés)", "phrase", "greetings", "u01-l01"],
  ["sure", "persze", "adverb", "conversation", "u06-l02"],
  ["of course", "természetesen", "phrase", "conversation", "u10-l01"],
  ["welcome back", "üdv újra", "phrase", "greetings", "u16-l01"],
  ["good luck", "sok sikert", "phrase", "conversation", "u16-l01"],
  ["congratulations", "gratulálok", "phrase", "family", "u16-l01", null, "A2"],

  // ===== Batch 2: closing the A1 core =====
  // question words
  ["when", "mikor", "adverb", "conversation", "u06-l01"],
  ["why", "miért", "adverb", "conversation", "u08-l02"],
  ["which", "melyik", "pronoun", "conversation", "u09-l02"],
  // common nouns
  ["thing", "dolog", "noun", "conversation", "u07-l02", ["thing", "things"]],
  ["way", "út / mód", "noun", "town", "u09-l01", ["way", "ways"]],
  ["part", "rész", "noun", "conversation", "u08-l02", ["part", "parts"], "A2"],
  ["side", "oldal", "noun", "town", "u09-l01", ["side", "sides"]],
  ["kind", "fajta", "noun", "opinions", "u08-l02", ["kind", "kinds"]],
  ["end", "vég", "noun", "conversation", "u12-l02", ["end", "ends"]],
  ["group", "csoport", "noun", "conversation", "u16-l01", ["group", "groups"], "A2"],
  ["story", "történet", "noun", "hobbies", "u08-l01", ["story", "stories"]],
  ["song", "dal", "noun", "hobbies", "u08-l01", ["song", "songs"]],
  ["game", "játék", "noun", "hobbies", "u08-l01", ["game", "games"]],
  ["party", "buli / parti", "noun", "family", "u16-l01", ["party", "parties"]],
  ["present", "ajándék", "noun", "family", "u16-l01", ["present", "presents"]],
  ["photo", "fénykép", "noun", "hobbies", "u08-l01", ["photo", "photos"]],
  ["picture", "kép", "noun", "hobbies", "u08-l01", ["picture", "pictures"]],
  ["letter", "levél / betű", "noun", "phone", "u07-l02", ["letter", "letters"]],
  ["news", "hír(ek)", "noun", "phone", "u07-l02"],
  ["idea", "ötlet", "noun", "opinions", "u06-l02", ["idea", "ideas"]],
  ["office", "iroda", "noun", "town", "u09-l01", ["office", "offices"]],
  ["building", "épület", "noun", "town", "u09-l01", ["building", "buildings"]],
  ["box", "doboz", "noun", "home", "u05-l02", ["box", "boxes"]],
  ["bottle", "üveg (palack)", "noun", "food", "u05-l02", ["bottle", "bottles"]],
  ["glass", "pohár", "noun", "food", "u05-l02", ["glass", "glasses"]],
  ["plate", "tányér", "noun", "food", "u05-l02", ["plate", "plates"]],
  ["knife", "kés", "noun", "food", "u05-l02", ["knife", "knives"]],
  ["spoon", "kanál", "noun", "food", "u05-l02", ["spoon", "spoons"]],
  ["fork", "villa", "noun", "food", "u05-l02", ["fork", "forks"]],
  ["meal", "étkezés", "noun", "food", "u05-l01", ["meal", "meals"]],
  ["snack", "nasi / snack", "noun", "food", "u05-l01", ["snack", "snacks"], "A2"],
  ["cafe", "kávézó", "noun", "services", "u10-l01", ["cafe", "cafes"]],
  ["clock", "óra (fali)", "noun", "time", "u06-l01", ["clock", "clocks"]],
  ["watch", "karóra", "noun", "time", "u06-l01", ["watch", "watches"]],
  ["umbrella", "esernyő", "noun", "weather", "u06-l02", ["umbrella", "umbrellas"]],
  ["colour", "szín", "noun", "colours", "u08-l02", ["colour", "colours"]],
  ["holiday", "ünnep / szabadnap", "noun", "time", "u06-l01", ["holiday", "holidays"]],
  ["birthday", "születésnap", "noun", "family", "u16-l01", ["birthday", "birthdays"]],
  ["weekend", "hétvége", "noun", "time", "u06-l02"],
  // common verbs
  ["talk", "beszélgetni", "verb", "conversation", "u07-l02", ["talk", "talks", "talked"]],
  ["smile", "mosolyogni", "verb", "feelings", "u16-l01", ["smile", "smiles", "smiled"]],
  ["laugh", "nevetni", "verb", "feelings", "u16-l01", ["laugh", "laughs", "laughed"], "A2"],
  ["jump", "ugrani", "verb", "hobbies", "u08-l01", ["jump", "jumps", "jumped"]],
  ["draw", "rajzolni", "verb", "hobbies", "u08-l01", ["draw", "draws", "drew"]],
  ["paint", "festeni", "verb", "hobbies", "u08-l01", ["paint", "paints", "painted"]],
  ["cut", "vágni", "verb", "food", "u05-l02", ["cut", "cuts"]],
  ["catch", "elkapni / elérni", "verb", "transport", "u09-l02", ["catch", "catches", "caught"], "A2"],
  ["win", "nyerni", "verb", "hobbies", "u08-l01", ["win", "wins", "won"], "A2"],
  ["invite", "meghívni", "verb", "family", "u16-l01", ["invite", "invites", "invited"], "A2"],
  ["fill", "megtölteni / kitölteni", "verb", "services", "u10-l02", ["fill", "fills", "filled"], "A2"],
  ["choose", "választani", "verb", "services", "u10-l01", ["choose", "chooses", "chose"], "A2"],
  ["thank", "megköszönni", "verb", "conversation", "u01-l01", ["thank", "thanks", "thanked"]],
  ["worry", "aggódni", "verb", "feelings", "u15-l01", ["worry", "worries", "worried"], "A2"],
  ["practise", "gyakorolni", "verb", "teaching", "u11-l01", ["practise", "practises", "practised"], "A2"],
  ["decide", "eldönteni", "verb", "plans", "u13-l01", ["decide", "decides", "decided"], "A2"],
  ["spend", "költeni / tölteni", "verb", "shopping", "u12-l02", ["spend", "spends", "spent"], "A2"],
  ["save", "megspórolni / menteni", "verb", "technology", "u11-l02", ["save", "saves", "saved"], "A2"],
  ["rain", "esni (eső)", "verb", "weather", "u06-l02", ["rain", "rains", "rained"]],
  // adjectives
  ["low", "alacsony (tárgy)", "adjective", "town", "u09-l01"],
  ["cool", "hűvös / menő", "adjective", "weather", "u06-l02"],
  ["wonderful", "csodálatos", "adjective", "opinions", "u08-l02"],
  ["great", "nagyszerű", "adjective", "opinions", "u08-l02"],
  ["true", "igaz", "adjective", "conversation", "u08-l02"],
  ["real", "valódi", "adjective", "opinions", "u08-l02", null, "A2"],
  ["best", "legjobb", "adjective", "opinions", "u08-l02"],
  ["next", "következő", "adjective", "time", "u06-l01"],
  ["last", "utolsó / múlt", "adjective", "past", "u12-l01"],
  ["other", "másik", "adjective", "conversation", "u09-l02"],
  ["every", "minden", "determiner", "daily-life", "u04-l01"],
  ["perfect", "tökéletes", "adjective", "opinions", "u08-l02", null, "A2"],
  ["terrible", "szörnyű", "adjective", "opinions", "u08-l02", null, "A2"],
  // adverbs / prepositions
  ["then", "aztán / akkor", "adverb", "conversation", "u12-l02"],
  ["into", "-ba / -be", "preposition", "town", "u09-l01"],
  ["through", "át / keresztül", "preposition", "town", "u09-l01", null, "A2"],
  ["around", "körül", "preposition", "town", "u09-l01", null, "A2"],
  ["quite", "elég(gé)", "adverb", "opinions", "u08-l02", null, "A2"],
  ["almost", "majdnem", "adverb", "conversation", "u12-l02", null, "A2"],

  // ===== Batch 3: final A1 core =====
  ["age", "kor / életkor", "noun", "identity", "u01-l02", ["age", "ages"]],
  ["address", "cím", "noun", "identity", "u01-l02", ["address", "addresses"]],
  ["size", "méret", "noun", "shopping", "u05-l02", ["size", "sizes"]],
  ["front", "eleje / elöl", "noun", "town", "u09-l01"],
  ["back", "hátulja / hát", "noun", "town", "u09-l01"],
  ["middle", "közép", "noun", "town", "u09-l01", null, "A2"],
  ["top", "teteje", "noun", "town", "u09-l01"],
  ["ground", "föld / talaj", "noun", "town", "u09-l01"],
  ["north", "észak", "noun", "town", "u09-l01", null, "A2"],
  ["south", "dél", "noun", "town", "u09-l01", null, "A2"],
  ["east", "kelet", "noun", "town", "u09-l01", null, "A2"],
  ["west", "nyugat", "noun", "town", "u09-l01", null, "A2"],
  ["moon", "hold", "noun", "weather", "u06-l02"],
  ["grass", "fű", "noun", "weather", "u06-l02"],
  ["field", "mező", "noun", "weather", "u06-l02", ["field", "fields"], "A2"],
  ["star", "csillag", "noun", "weather", "u06-l02", ["star", "stars"]],
  ["pull", "húzni", "verb", "daily-life", "u09-l01", ["pull", "pulls", "pulled"]],
  ["push", "tolni / nyomni", "verb", "daily-life", "u09-l01", ["push", "pushes", "pushed"]],
  ["hold", "tartani / fogni", "verb", "daily-life", "u15-l01", ["hold", "holds", "held"], "A2"],
  ["miss", "lekésni / hiányozni", "verb", "travel", "u14-l02", ["miss", "misses", "missed"], "A2"],
  ["keep", "megtartani", "verb", "daily-life", "u13-l02", ["keep", "keeps", "kept"], "A2"],
  ["let", "hagyni / engedni", "verb", "conversation", "u11-l01", ["let", "lets"], "A2"],
  ["hate", "utálni", "verb", "opinions", "u08-l01", ["hate", "hates", "hated"], "A2"],
  ["prefer", "jobban szeretni", "verb", "opinions", "u08-l02", ["prefer", "prefers", "preferred"], "A2"],
  ["agree", "egyetérteni", "verb", "opinions", "u08-l02", ["agree", "agrees", "agreed"], "A2"],
  ["open", "nyitva", "adjective", "services", "u10-l01"],
  ["closed", "zárva", "adjective", "services", "u10-l01"],
  ["heavy", "nehéz (súly)", "adjective", "travel", "u13-l02", null, "A2"],
  ["soft", "puha", "adjective", "opinions", "u08-l02", null, "A2"],
  ["pretty", "csinos / szép", "adjective", "opinions", "u08-l02", null, "A2"],
  ["last", "tartani (időben)", "verb", "flying", "u15-l02", ["last", "lasts", "lasted"], "A2"],
  ["seat", "ülőhely", "noun", "transport", "u09-l02", ["seat", "seats"]],
  ["window", "ablak (ülés)", "noun", "flying", "u15-l01"],
  ["glad", "örülök", "adjective", "feelings", "u16-l01"],
  ["welcome", "üdvözöllek", "phrase", "greetings", "u01-l02"],
];

// A handful of extra receptive items (understood, not required productively).
export const EXTRA_RECEPTIVE = [
  ["gate number", "kapuszám", "phrase", "airport"],
  ["boarding pass", "beszállókártya", "phrase", "airport"],
  ["hand luggage", "kézipoggyász", "phrase", "airport"],
  ["window seat", "ablak melletti ülés", "phrase", "flying"],
  ["aisle seat", "folyosó melletti ülés", "phrase", "flying"],
  ["emergency", "vészhelyzet", "noun", "flying"],
  ["please fasten your seatbelt", "kérjük, kapcsolja be az övét", "phrase", "flying"],
  ["single room", "egyágyas szoba", "phrase", "hotel"],
  ["double room", "kétágyas szoba", "phrase", "hotel"],
  ["check-out", "kijelentkezés", "noun", "hotel"],
  ["main course", "főétel", "noun", "services"],
  ["still water", "szénsavmentes víz", "phrase", "services"],
  ["sparkling water", "szénsavas víz", "phrase", "services"],
  ["return ticket", "menettérti jegy", "phrase", "transport"],
  ["single ticket", "egyszeri jegy", "phrase", "transport"],
  ["how long", "mennyi ideig", "phrase", "conversation"],
  ["what time", "hány órakor", "phrase", "time"],
  ["turn left", "fordulj balra", "phrase", "town"],
  ["turn right", "fordulj jobbra", "phrase", "town"],
  ["go straight on", "menj egyenesen", "phrase", "town"],
];
