// Phase 3 (Wave A) — productive vocabulary top-up toward the 730–770 EVP A1 target.
// [headword, hu, partOfSpeech, theme, firstLesson, acceptedForms?, level?]  A2 flagged.
export const EXTRA2 = [
  // verbs
  ["return", "visszatérni / visszaadni", "verb", "travel", "u13-l01", ["return", "returns", "returned"], "A2"],
  ["follow", "követni", "verb", "town", "u09-l01", ["follow", "follows", "followed"]],
  ["move", "mozogni / költözni", "verb", "daily-life", "u04-l01", ["move", "moves", "moved"]],
  ["fall", "esni / elesni", "verb", "daily-life", "u15-l01", ["fall", "falls", "fell"], "A2"],
  ["ring", "csengetni / felhívni", "verb", "phone", "u07-l01", ["ring", "rings", "rang"], "A2"],
  ["knock", "kopogni", "verb", "home", "u04-l02", ["knock", "knocks", "knocked"]],
  ["borrow", "kölcsönkérni", "verb", "shopping", "u05-l02", ["borrow", "borrows", "borrowed"], "A2"],
  ["lose", "elveszíteni", "verb", "travel", "u14-l02", ["lose", "loses", "lost"], "A2"],
  ["ride", "lovagolni / biciklizni", "verb", "hobbies", "u08-l01", ["ride", "rides", "rode"]],
  ["climb", "mászni", "verb", "hobbies", "u08-l01", ["climb", "climbs", "climbed"], "A2"],
  ["fix", "megjavítani", "verb", "technology", "u11-l02", ["fix", "fixes", "fixed"], "A2"],
  ["break", "eltörni", "verb", "home", "u10-l02", ["break", "breaks", "broke"], "A2"],
  ["build", "építeni", "verb", "hobbies", "u08-l01", ["build", "builds", "built"], "A2"],
  ["grow", "nőni / termeszteni", "verb", "hobbies", "u08-l01", ["grow", "grows", "grew"], "A2"],
  ["feed", "etetni", "verb", "daily-life", "u04-l01", ["feed", "feeds", "fed"], "A2"],
  ["drop", "leejteni", "verb", "daily-life", "u15-l01", ["drop", "drops", "dropped"], "A2"],
  ["enter", "belépni", "verb", "town", "u09-l01", ["enter", "enters", "entered"], "A2"],
  ["turn on", "bekapcsolni", "verb", "technology", "u11-l01", ["turn on", "turns on", "turned on"]],
  ["wait for", "várni vkire", "verb", "conversation", "u07-l01", ["wait for", "waits for", "waited for"]],
  ["look for", "keresni", "verb", "town", "u09-l01", ["look for", "looks for", "looked for"], "A2"],
  // nouns — household & objects
  ["cup", "csésze / bögre", "noun", "food", "u05-l02", ["cup", "cups"]],
  ["pot", "fazék", "noun", "food", "u05-l02", ["pot", "pots"]],
  ["pan", "serpenyő", "noun", "food", "u05-l02", ["pan", "pans"]],
  ["towel", "törölköző", "noun", "home", "u04-l02", ["towel", "towels"]],
  ["mirror", "tükör", "noun", "home", "u04-l02", ["mirror", "mirrors"]],
  ["clock", "óra (fali)", "noun", "home", "u04-l02", ["clock", "clocks"]],
  ["key", "kulcs", "noun", "home", "u04-l02", ["key", "keys"]],
  ["bag", "táska", "noun", "shopping", "u05-l02", ["bag", "bags"]],
  ["basket", "kosár", "noun", "shopping", "u05-l02", ["basket", "baskets"], "A2"],
  ["list", "lista", "noun", "shopping", "u05-l02", ["list", "lists"]],
  // nouns — transport & places
  ["boat", "csónak / hajó", "noun", "transport", "u09-l02", ["boat", "boats"]],
  ["bicycle", "kerékpár", "noun", "transport", "u09-l02", ["bicycle", "bicycles"]],
  ["airport bus", "reptéri busz", "phrase", "transport", "u14-l01", null, "A2"],
  ["corner shop", "sarki bolt", "phrase", "town", "u09-l01", null, "A2"],
  ["bench", "pad", "noun", "town", "u09-l01", ["bench", "benches"], "A2"],
  // nouns — nature & animals
  ["hill", "domb", "noun", "weather", "u06-l02", ["hill", "hills"], "A2"],
  ["field", "mező", "noun", "weather", "u06-l02", ["field", "fields"], "A2"],
  ["duck", "kacsa", "noun", "hobbies", "u08-l02", ["duck", "ducks"]],
  ["rabbit", "nyúl", "noun", "hobbies", "u08-l02", ["rabbit", "rabbits"]],
  // nouns — food
  ["chicken", "csirke", "noun", "food", "u05-l01", null],
  ["carrot", "sárgarépa", "noun", "food", "u05-l01", ["carrot", "carrots"]],
  ["lemon", "citrom", "noun", "food", "u05-l01", ["lemon", "lemons"]],
  ["biscuit", "keksz", "noun", "food", "u05-l01", ["biscuit", "biscuits"], "A2"],
  ["honey", "méz", "noun", "food", "u05-l01"],
  // adjectives
  ["bright", "világos / ragyogó", "adjective", "weather", "u06-l02", null, "A2"],
  ["sweet", "édes", "adjective", "food", "u05-l01"],
  ["fresh", "friss", "adjective", "food", "u05-l01"],
  ["sleepy", "álmos", "adjective", "feelings", "u15-l01"],
  ["lucky", "szerencsés", "adjective", "feelings", "u16-l01", null, "A2"],
  ["famous", "híres", "adjective", "opinions", "u08-l02", null, "A2"],
  ["modern", "modern", "adjective", "opinions", "u08-l02", null, "A2"],
  ["comfortable", "kényelmes", "adjective", "feelings", "u10-l02", null, "A2"],
  ["wide", "széles", "adjective", "town", "u09-l01", null, "A2"],
  ["deep", "mély", "adjective", "weather", "u06-l02", null, "A2"],
  // adverbs / functional
  ["already", "már", "adverb", "conversation", "u12-l02", null, "A2"],
  ["still", "még mindig", "adverb", "conversation", "u12-l02", null, "A2"],
  ["together", "együtt", "adverb", "family", "u16-l01"],
  ["outside", "kint", "adverb", "home", "u04-l02"],
  ["inside", "bent", "adverb", "home", "u04-l02"],
];
