// Pronunciation & spelling-family data. No IPA shown to the learner.
// Spelling families for the word-builder engine.
// [id, label(en), labelHu, note(en), noteHu, items: [ [onset, rime, word] ... ] ]
export const SPELLING_FAMILIES = [
  ["sf_a_e", "The a…e family (say the letter A)", "Az a…e család (az A betű nevét mondd)",
    "In these words a…e often sounds like the name of the letter A.",
    "Ezekben a szavakban az a…e gyakran úgy hangzik, mint az A betű neve.",
    [["m", "ake", "make"], ["c", "ake", "cake"], ["n", "ame", "name"], ["g", "ame", "game"], ["l", "ate", "late"], ["pl", "ane", "plane"]]],
  ["sf_i_e", "The i…e family (say the letter I)", "Az i…e család (az I betű nevét mondd)",
    "Here i…e often sounds like the name of the letter I. But careful: give and live are different.",
    "Itt az i…e gyakran úgy hangzik, mint az I betű neve. De vigyázz: a give és a live más.",
    [["t", "ime", "time"], ["f", "ive", "five"], ["n", "ice", "nice"], ["l", "ike", "like"], ["wh", "ite", "white"]]],
  ["sf_o_e", "The o…e family (say the letter O)", "Az o…e család (az O betű nevét mondd)",
    "In these words o…e often sounds like the name of the letter O.",
    "Ezekben a szavakban az o…e gyakran úgy hangzik, mint az O betű neve.",
    [["h", "ome", "home"], ["ph", "one", "phone"], ["n", "ose", "nose"], ["cl", "ose", "close"]]],
  ["sf_ee", "The ee family", "Az ee család",
    "ee usually sounds like a long 'ee'.",
    "Az ee általában hosszú 'í'-nek hangzik.",
    [["s", "ee", "see"], ["m", "eet", "meet"], ["thr", "ee", "three"], ["w", "eek", "week"], ["gr", "een", "green"]]],
  ["sf_ea", "The ea family", "Az ea család",
    "ea often sounds like 'ee', but not always (bread is different).",
    "Az ea gyakran 'í'-nek hangzik, de nem mindig (a bread más).",
    [["t", "ea", "tea"], ["e", "at", "eat"], ["r", "ead", "read"], ["m", "eat", "meat"]]],
  ["sf_ight", "The -ight family", "A -ight család",
    "In -ight the 'gh' is silent. It sounds like the letter I plus t.",
    "A -ight-ban a 'gh' néma. Úgy hangzik, mint az I betű neve + t.",
    [["n", "ight", "night"], ["fl", "ight", "flight"], ["r", "ight", "right"], ["l", "ight", "light"]]],
  ["sf_oo", "The oo family", "Az oo család",
    "oo is often a long 'oo' sound.",
    "Az oo gyakran hosszú 'ú' hang.",
    [["f", "ood", "food"], ["s", "oon", "soon"], ["r", "oom", "room"], ["af", "ternoon", "afternoon"]]],
];

// Sound-focus groups (listening / awareness). Contrast pairs, taught gently.
// [id, focusEn, focusHu, tipEn, tipHu, examples[[word, ...]] , minimalPairs[[a,b]] ]
export const SOUND_FOCUS = [
  ["pf_th", "The 'th' sound", "A 'th' hang",
    "Put your tongue lightly between your teeth for th in the, three, thank you.",
    "A th-nál (the, three, thank you) tedd a nyelved lazán a fogaid közé.",
    ["the", "three", "thank you", "this", "mother"], [["think", "sink"], ["three", "tree"]]],
  ["pf_wv", "'w' and 'v'", "A 'w' és a 'v'",
    "For w round your lips (water). For v use your teeth on your lip (very).",
    "A w-nél kerekítsd az ajkad (water). A v-nél a fogad az ajkadhoz (very).",
    ["water", "we", "work", "very", "visit", "video"], [["west", "vest"], ["wine", "vine"]]],
  ["pf_finals", "Final -s endings", "A szóvégi -s",
    "Listen to the last sound: books, names, buses. Three gentle patterns, not a rule to memorise.",
    "Figyeld az utolsó hangot: books, names, buses. Három lágy minta, nem szabály.",
    ["books", "names", "buses", "sisters", "watches"], []],
  ["pf_ed", "Past -ed endings", "A múlt idő -ed vége",
    "Listen: visited, cooked, lived. Three gentle patterns, not a rule to memorise.",
    "Figyeld: visited, cooked, lived. Három lágy minta, nem szabály.",
    ["visited", "cooked", "lived", "worked", "wanted"], []],
  ["pf_stress", "Word stress", "Szóhangsúly",
    "One part of the word is stronger: HO-tel, com-PU-ter, a-FRAID.",
    "A szó egyik része erősebb: HO-tel, com-PU-ter, a-FRAID.",
    ["hotel", "computer", "afraid", "restaurant", "family"], []],
  ["pf_question", "Question and statement melody", "Kérdés és kijelentés dallama",
    "Many yes/no questions go up at the end. Wh-questions usually go down.",
    "Sok eldöntendő kérdés a végén felmegy. A kérdőszós kérdés általában lemegy.",
    ["Can you hear me?", "Where is my gate?", "Are you ready?"], []],
];
