// Pronunciation & listening — a two-stage path inspired by the pedagogy of
// elementary pronunciation courses (e.g. "English Pronunciation in Use").
// STAGE 1: the SOUNDS themselves, anchored to keywords, NEVER using IPA.
// STAGE 2: the (hard!) relationship between SPELLING and SOUND.
// A separate strand covers word stress, sentence stress and intonation.
// No IPA is ever shown to the learner. Internal ids may hint at phonemes.

// A short description of the journey, shown in the app.
export const PATH = {
  intro: {
    en: "We learn pronunciation in two steps. First we listen to the sounds of English, using easy example words — no strange symbols. Then we look at how English spelling and sound fit together, which is the tricky part.",
    hu: "A kiejtést két lépésben tanuljuk. Először meghallgatjuk az angol hangokat egyszerű példaszavakkal — furcsa jelek nélkül. Utána megnézzük, hogyan illik össze az angol írás és kiejtés — ez a nehéz rész.",
  },
  stages: [
    { id: "stage-1", label: { en: "Step 1 · The sounds", hu: "1. lépés · A hangok" } },
    { id: "stage-2", label: { en: "Step 2 · Spelling & sound", hu: "2. lépés · Írás és kiejtés" } },
    { id: "stage-3", label: { en: "Step 3 · Stress & melody", hu: "3. lépés · Hangsúly és dallam" } },
  ],
};

// ---- STAGE 1: SOUNDS (keyword-anchored, no IPA) ----
// [id, stage, order, focusEn, focusHu, tipEn, tipHu, examples[], minimalPairs[[a,b]]]
export const SOUND_FOCUS = [
  // vowels — short
  ["snd_short_vowels", "stage-1", 1, "Short vowels", "Rövid magánhangzók",
    "Listen to the short vowel in each word: cat, bed, sit, hot, cup. They are quick and clear.",
    "Figyeld a rövid magánhangzót: cat, bed, sit, hot, cup. Rövidek és tiszták.",
    ["cat", "bed", "sit", "hot", "cup"], [["sit", "set"], ["cat", "cut"]]],
  ["snd_long_vowels", "stage-1", 2, "Long vowels", "Hosszú magánhangzók",
    "Some vowels are longer: see, too, car, more. Let the sound last a little longer.",
    "Néhány magánhangzó hosszabb: see, too, car, more. Hagyd egy kicsit tovább szólni.",
    ["see", "too", "car", "more", "her"], [["ship", "sheep"], ["full", "fool"]]],
  ["snd_ee_i", "stage-1", 3, "The 'ee' and 'i' sounds", "Az 'ee' és 'i' hang",
    "Hear the difference: this (short) and these (long). English needs both.",
    "Halld a különbséget: this (rövid) és these (hosszú). Mindkettő kell.",
    ["this", "these", "it", "eat", "live", "leave"], [["it", "eat"], ["live", "leave"]]],
  // consonants — the hard ones for Hungarian speakers
  ["snd_th", "stage-1", 4, "The two 'th' sounds", "A két 'th' hang",
    "Put your tongue lightly between your teeth. Soft: thank you, three. Voiced: this, mother.",
    "Tedd a nyelved lazán a fogaid közé. Lágy: thank you, three. Zöngés: this, mother.",
    ["thank you", "three", "this", "mother", "the"], [["think", "sink"], ["three", "tree"]]],
  ["snd_wv", "stage-1", 5, "'w' and 'v'", "A 'w' és a 'v'",
    "For w round your lips (water, we). For v put your teeth on your lip (very, visit).",
    "A w-nél kerekítsd az ajkad (water, we). A v-nél a fogad az ajkadhoz (very, visit).",
    ["water", "we", "work", "very", "visit", "video"], [["west", "vest"], ["wine", "vine"]]],
  ["snd_h", "stage-1", 6, "The 'h' sound", "A 'h' hang",
    "Breathe out gently at the start: hello, home, help. Don't drop it.",
    "Lehelj ki finoman a szó elején: hello, home, help. Ne hagyd el.",
    ["hello", "home", "help", "have", "how"], [["eat", "heat"], ["and", "hand"]]],
  ["snd_shchj", "stage-1", 7, "'sh', 'ch' and 'j'", "A 'sh', 'ch' és 'j'",
    "sh is soft (she, ship); ch is harder (chair, teacher); j is like the start of July.",
    "A sh lágy (she, ship); a ch keményebb (chair, teacher); a j olyan, mint a July eleje.",
    ["she", "ship", "chair", "teacher", "July", "juice"], [["ship", "chip"], ["cheap", "jeep"]]],
  ["snd_ng", "stage-1", 8, "The 'ng' sound", "Az 'ng' hang",
    "One soft sound at the back, no hard g: morning, evening, going, thing.",
    "Egy lágy hang hátul, kemény g nélkül: morning, evening, going, thing.",
    ["morning", "evening", "going", "thing", "reading"], []],
  ["snd_r", "stage-1", 9, "The English 'r'", "Az angol 'r'",
    "Soft, not rolled: right, red, three, sorry. British English often keeps it gentle.",
    "Lágy, nem pergetett: right, red, three, sorry. A brit angolban gyakran finom.",
    ["right", "red", "three", "sorry", "very"], []],
  ["snd_final_cons", "stage-1", 10, "Final consonants", "Szóvégi mássalhangzók",
    "Finish the last sound clearly: goodnight, help, first, next. Don't let it disappear.",
    "Ejtsd tisztán az utolsó hangot: goodnight, help, first, next. Ne tűnjön el.",
    ["night", "help", "first", "next", "airport"], [["bad", "bat"], ["nine", "night"]]],
  ["snd_s_endings", "stage-1", 11, "'-s' endings", "A '-s' végződések",
    "Three gentle patterns: books, names, buses. Just listen — no rule to memorise.",
    "Három lágy minta: books, names, buses. Csak hallgasd — nincs szabály.",
    ["books", "names", "buses", "sisters", "watches"], []],
  ["snd_ed_endings", "stage-1", 12, "Past '-ed' endings", "A múlt idő '-ed' vége",
    "Three gentle patterns: visited, cooked, lived. Just listen — no rule to memorise.",
    "Három lágy minta: visited, cooked, lived. Csak hallgasd — nincs szabály.",
    ["visited", "cooked", "lived", "worked", "wanted"], []],

  // ---- STAGE 3 strand: stress & melody (suprasegmental) ----
  ["str_word", "stage-3", 1, "Word stress", "Szóhangsúly",
    "One part of the word is stronger: HO-tel, com-PU-ter, a-FRAID, res-TAU-rant.",
    "A szó egyik része erősebb: HO-tel, com-PU-ter, a-FRAID, res-TAU-rant.",
    ["hotel", "computer", "afraid", "restaurant", "family"], []],
  ["str_sentence", "stage-3", 2, "Sentence stress", "Mondathangsúly",
    "The important words are louder: 'I'd like SOME WATER, please.' Small words stay light.",
    "A fontos szavak hangosabbak: 'I'd like SOME WATER, please.' A kis szavak halkak.",
    ["I'd like some water", "Where is my gate", "Can you help me"], []],
  ["str_question", "stage-3", 3, "Question & statement melody", "Kérdés és kijelentés dallama",
    "Many yes/no questions rise at the end; wh-questions and statements usually fall.",
    "Sok eldöntendő kérdés a végén felmegy; a kérdőszós kérdés és a kijelentés általában lemegy.",
    ["Can you hear me?", "Where is my gate?", "I am from Hungary."], []],
  ["str_chunking", "stage-3", 4, "Chunking & pausing", "Tagolás és szünet",
    "Say short groups with small pauses: 'Could you help me, / please?' It sounds calm and clear.",
    "Mondd rövid csoportokban, kis szünettel: 'Could you help me, / please?' Nyugodt és érthető.",
    ["Could you help me, please?", "I am afraid of flying.", "When will we land?"], []],
];

// ---- STAGE 2: SPELLING <-> SOUND (the tricky English relationship) ----
// [id, order, label(en), labelHu, note(en), noteHu, items:[[onset,rime,word]], caution?]
export const SPELLING_FAMILIES = [
  ["sf_magic_e_a", "1", "The a…e pattern (say the letter A)", "Az a…e minta (az A betű neve)",
    "A silent 'e' at the end often makes 'a' say its name: make, name, late.",
    "A szóvégi néma 'e' miatt az 'a' gyakran a saját nevét mondja: make, name, late.",
    [["m", "ake", "make"], ["c", "ake", "cake"], ["n", "ame", "name"], ["g", "ame", "game"], ["l", "ate", "late"], ["pl", "ane", "plane"]]],
  ["sf_magic_e_i", "2", "The i…e pattern (say the letter I)", "Az i…e minta (az I betű neve)",
    "Silent 'e' often makes 'i' say its name: time, five, nice. Careful: give and live are different!",
    "A néma 'e' miatt az 'i' gyakran a nevét mondja: time, five, nice. Vigyázz: a give és a live más!",
    [["t", "ime", "time"], ["f", "ive", "five"], ["n", "ice", "nice"], ["l", "ike", "like"], ["wh", "ite", "white"]],
    { en: "Not always! In give and live the 'i' is short. Spelling does not always tell you the sound.", hu: "Nem mindig! A give és a live szóban az 'i' rövid. Az írás nem mindig árulja el a hangot." }],
  ["sf_magic_e_o", "3", "The o…e pattern (say the letter O)", "Az o…e minta (az O betű neve)",
    "Silent 'e' often makes 'o' say its name: home, phone, close.",
    "A néma 'e' miatt az 'o' gyakran a nevét mondja: home, phone, close.",
    [["h", "ome", "home"], ["ph", "one", "phone"], ["n", "ose", "nose"], ["cl", "ose", "close"]]],
  ["sf_ee", "4", "The 'ee' spelling", "Az 'ee' írás",
    "'ee' is usually a long 'ee' sound: see, meet, week, green.",
    "Az 'ee' általában hosszú 'í': see, meet, week, green.",
    [["s", "ee", "see"], ["m", "eet", "meet"], ["thr", "ee", "three"], ["w", "eek", "week"], ["gr", "een", "green"]]],
  ["sf_ea", "5", "The 'ea' spelling", "Az 'ea' írás",
    "'ea' is often a long 'ee' (tea, eat), but sometimes not (bread). Two words, same letters, different sound.",
    "Az 'ea' gyakran hosszú 'í' (tea, eat), de néha nem (bread). Ugyanaz a betű, más hang.",
    [["t", "ea", "tea"], ["e", "at", "eat"], ["r", "ead", "read"], ["m", "eat", "meat"]],
    { en: "'bread' and 'head' use 'ea' but sound short. Listen, don't only trust the spelling.", hu: "A 'bread' és 'head' 'ea'-t ír, de rövid. Hallgasd, ne csak az írásban bízz." }],
  ["sf_igh", "6", "The '-igh(t)' spelling", "A '-igh(t)' írás",
    "In 'igh' the 'gh' is silent; it sounds like the letter I: night, light, right, flight.",
    "Az 'igh'-ben a 'gh' néma; úgy hangzik, mint az I betű: night, light, right, flight.",
    [["n", "ight", "night"], ["fl", "ight", "flight"], ["r", "ight", "right"], ["l", "ight", "light"]]],
  ["sf_oo", "7", "The 'oo' spelling", "Az 'oo' írás",
    "'oo' is often a long 'oo': food, soon, room, afternoon.",
    "Az 'oo' gyakran hosszú 'ú': food, soon, room, afternoon.",
    [["f", "ood", "food"], ["s", "oon", "soon"], ["r", "oom", "room"], ["aft", "ernoon", "afternoon"]]],
  ["sf_ph", "8", "'ph' sounds like 'f'", "A 'ph' 'f'-nek hangzik",
    "The letters 'ph' make an 'f' sound: phone, photo, elephant.",
    "A 'ph' betűk 'f' hangot adnak: phone, photo, elephant.",
    [["ph", "one", "phone"], ["ph", "oto", "photo"]]],
  ["sf_wh", "9", "The 'wh' spelling", "A 'wh' írás",
    "'wh' is usually a 'w' sound: what, where, when, white. The 'h' is quiet.",
    "A 'wh' általában 'w' hang: what, where, when, white. A 'h' halk.",
    [["wh", "at", "what"], ["wh", "ere", "where"], ["wh", "en", "when"], ["wh", "ite", "white"]]],
  ["sf_tion", "10", "The '-tion' ending", "A '-tion' végződés",
    "'-tion' sounds like 'shun': station, question, information.",
    "A '-tion' úgy hangzik: 'sön': station, question, information.",
    [["sta", "tion", "station"], ["ques", "tion", "question"]]],
  ["sf_ar_or", "11", "'ar' and 'or'", "Az 'ar' és 'or'",
    "'ar' as in car, far; 'or' as in more, airport. Different mouth shapes.",
    "Az 'ar' mint a car, far; az 'or' mint a more, airport. Más szájforma.",
    [["c", "ar", "car"], ["f", "ar", "far"], ["m", "ore", "more"], ["airp", "ort", "airport"]]],
];
