// Phase 3 (Wave A) — receptive vocabulary expansion.
// Understood in listening/reading; not required productively. [head, hu, pos, theme]
// Duplicate headwords already present are skipped by the generator.
export const RECEPTIVE_BIG = [
  // ---- airport / flying ----
  ["boarding gate", "beszállókapu", "phrase", "airport"], ["departure lounge", "indulási váró", "phrase", "airport"],
  ["baggage claim", "poggyászkiadó", "phrase", "airport"], ["customs", "vám", "noun", "airport"],
  ["duty free", "vámmentes bolt", "phrase", "airport"], ["terminal", "terminál", "noun", "airport"],
  ["trolley", "poggyászkocsi", "noun", "airport"], ["overhead locker", "csomagtartó (fejfeletti)", "phrase", "flying"],
  ["life jacket", "mentőmellény", "phrase", "flying"], ["oxygen mask", "oxigénmaszk", "phrase", "flying"],
  ["cabin", "utastér", "noun", "flying"], ["cockpit", "pilótafülke", "noun", "flying"],
  ["take off", "felszállás", "phrase", "flying"], ["landing", "leszállás", "noun", "flying"],
  ["tray table", "lehajtható asztalka", "phrase", "flying"], ["window seat", "ablak melletti hely", "phrase", "flying"],
  ["aisle", "folyosó (repülő)", "noun", "flying"], ["altitude", "magasság", "noun", "flying"],
  ["seatbelt sign", "öv-jelzés", "phrase", "flying"], ["boarding time", "beszállási idő", "phrase", "airport"],
  // ---- hotel / services ----
  ["reception desk", "recepciós pult", "phrase", "hotel"], ["room service", "szobaszerviz", "phrase", "hotel"],
  ["wake-up call", "ébresztő hívás", "phrase", "hotel"], ["luggage room", "csomagmegőrző", "phrase", "hotel"],
  ["twin room", "kétágyas (külön ágy)", "phrase", "hotel"], ["en suite", "fürdőszobás szoba", "phrase", "hotel"],
  ["towel", "törölköző", "noun", "hotel"], ["soap", "szappan", "noun", "hotel"],
  ["shampoo", "sampon", "noun", "hotel"], ["balcony", "erkély", "noun", "hotel"],
  ["view", "kilátás", "noun", "hotel"], ["booking reference", "foglalási szám", "phrase", "hotel"],
  ["waitress", "pincérnő", "noun", "services"], ["chef", "szakács", "noun", "services"],
  ["table for two", "asztal kettőnek", "phrase", "services"], ["side dish", "köret", "noun", "services"],
  ["tip", "borravaló", "noun", "services"], ["cash desk", "pénztár", "phrase", "services"],
  ["fitting room", "próbafülke", "phrase", "shopping"], ["special offer", "akció", "phrase", "shopping"],
  // ---- transport / town ----
  ["timetable", "menetrend", "noun", "transport"], ["platform number", "vágányszám", "phrase", "transport"],
  ["ticket machine", "jegyautomata", "phrase", "transport"], ["single fare", "egyszeri viteldíj", "phrase", "transport"],
  ["underground", "metró", "noun", "transport"], ["tram", "villamos", "noun", "transport"],
  ["taxi rank", "taxiállomás", "phrase", "transport"], ["traffic", "forgalom", "noun", "transport"],
  ["traffic lights", "közlekedési lámpa", "phrase", "town"], ["crossing", "átkelőhely", "noun", "town"],
  ["roundabout", "körforgalom", "noun", "town"], ["pavement", "járda", "noun", "town"],
  ["car park", "parkoló", "phrase", "town"], ["petrol station", "benzinkút", "phrase", "town"],
  ["post office", "posta", "phrase", "town"], ["town hall", "városháza", "phrase", "town"],
  ["shopping centre", "bevásárlóközpont", "phrase", "town"], ["bus stop", "buszmegálló", "phrase", "town"],
  ["motorway", "autópálya", "noun", "town"], ["signpost", "útjelző tábla", "noun", "town"],
  // ---- food & drink ----
  ["pasta", "tészta", "noun", "food"], ["chips", "sült krumpli", "noun", "food"],
  ["biscuit", "keksz", "noun", "food"], ["jam", "lekvár", "noun", "food"],
  ["honey", "méz", "noun", "food"], ["pepper", "bors / paprika", "noun", "food"],
  ["oil", "olaj", "noun", "food"], ["cream", "tejszín", "noun", "food"],
  ["yoghurt", "joghurt", "noun", "food"], ["sausage", "kolbász", "noun", "food"],
  ["ham", "sonka", "noun", "food"], ["pork", "sertéshús", "noun", "food"],
  ["beef", "marhahús", "noun", "food"], ["lemon", "citrom", "noun", "food"],
  ["strawberry", "eper", "noun", "food"], ["grapes", "szőlő", "noun", "food"],
  ["carrot", "sárgarépa", "noun", "food"], ["cucumber", "uborka", "noun", "food"],
  ["mushroom", "gomba", "noun", "food"], ["garlic", "fokhagyma", "noun", "food"],
  ["starter", "előétel", "noun", "food"], ["main course", "főétel", "phrase", "food"],
  ["lemonade", "limonádé", "noun", "food"], ["fizzy drink", "üdítő (szénsavas)", "phrase", "food"],
  // ---- home ----
  ["living room", "nappali", "phrase", "home"], ["dining room", "étkező", "phrase", "home"],
  ["hall", "előszoba", "noun", "home"], ["stairs", "lépcső", "noun", "home"],
  ["cupboard", "szekrény", "noun", "home"], ["wardrobe", "ruhásszekrény", "noun", "home"],
  ["shelf", "polc", "noun", "home"], ["curtain", "függöny", "noun", "home"],
  ["carpet", "szőnyeg", "noun", "home"], ["blanket", "takaró", "noun", "home"],
  ["pillow", "párna", "noun", "home"], ["cooker", "tűzhely", "noun", "home"],
  ["washing machine", "mosógép", "phrase", "home"], ["dishwasher", "mosogatógép", "noun", "home"],
  ["heating", "fűtés", "noun", "home"], ["light switch", "villanykapcsoló", "phrase", "home"],
  ["garden gate", "kertkapu", "phrase", "home"], ["garage", "garázs", "noun", "home"],
  // ---- body / health ----
  ["finger", "ujj", "noun", "body"], ["knee", "térd", "noun", "body"],
  ["neck", "nyak", "noun", "body"], ["shoulder", "váll", "noun", "body"],
  ["throat", "torok", "noun", "body"], ["stomach", "gyomor / has", "noun", "body"],
  ["skin", "bőr", "noun", "body"], ["heart", "szív", "noun", "body"],
  ["headache", "fejfájás", "noun", "health"], ["temperature", "láz / hőmérséklet", "noun", "health"],
  ["cold (illness)", "megfázás", "phrase", "health"], ["cough", "köhögés", "noun", "health"],
  ["prescription", "recept (orvosi)", "noun", "health"], ["appointment", "időpont (orvos)", "noun", "health"],
  ["chemist", "gyógyszertár", "noun", "health"], ["plaster", "sebtapasz", "noun", "health"],
  ["dentist", "fogorvos", "noun", "health"], ["emergency", "vészhelyzet", "noun", "health"],
  ["ambulance", "mentő", "noun", "health"], ["pain killer", "fájdalomcsillapító", "phrase", "health"],
  // ---- clothes ----
  ["socks", "zokni", "noun", "clothes"], ["jumper", "pulóver", "noun", "clothes"],
  ["scarf", "sál", "noun", "clothes"], ["gloves", "kesztyű", "noun", "clothes"],
  ["boots", "csizma", "noun", "clothes"], ["belt", "öv", "noun", "clothes"],
  ["skirt", "szoknya", "noun", "clothes"], ["blouse", "blúz", "noun", "clothes"],
  ["glasses", "szemüveg", "noun", "clothes"], ["umbrella", "esernyő", "noun", "clothes"],
  ["pocket", "zseb", "noun", "clothes"], ["button", "gomb", "noun", "clothes"],
  // ---- nature / weather ----
  ["countryside", "vidék", "noun", "weather"], ["forest", "erdő", "noun", "weather"],
  ["hill", "domb", "noun", "weather"], ["island", "sziget", "noun", "weather"],
  ["coast", "part", "noun", "weather"], ["valley", "völgy", "noun", "weather"],
  ["storm", "vihar", "noun", "weather"], ["fog", "köd", "noun", "weather"],
  ["ice", "jég", "noun", "weather"], ["temperature", "hőmérséklet", "noun", "weather"],
  ["degrees", "fok", "noun", "weather"], ["sunshine", "napsütés", "noun", "weather"],
  ["leaf", "levél (fa)", "noun", "weather"], ["insect", "rovar", "noun", "weather"],
  // ---- animals ----
  ["duck", "kacsa", "noun", "hobbies"], ["sheep", "birka", "noun", "hobbies"],
  ["pig", "malac", "noun", "hobbies"], ["rabbit", "nyúl", "noun", "hobbies"],
  ["mouse", "egér", "noun", "hobbies"], ["butterfly", "pillangó", "noun", "hobbies"],
  ["chicken (animal)", "csirke (állat)", "phrase", "hobbies"], ["goat", "kecske", "noun", "hobbies"],
  // ---- technology ----
  ["keyboard", "billentyűzet", "noun", "technology"], ["mouse (computer)", "egér (számítógép)", "phrase", "technology"],
  ["headphones", "fejhallgató", "noun", "technology"], ["charger", "töltő", "noun", "technology"],
  ["battery", "akkumulátor", "noun", "technology"], ["wifi", "wifi", "noun", "technology"],
  ["link", "hivatkozás / link", "noun", "technology"], ["file", "fájl", "noun", "technology"],
  ["folder", "mappa", "noun", "technology"], ["settings", "beállítások", "noun", "technology"],
  ["update", "frissítés", "noun", "technology"], ["volume", "hangerő", "noun", "technology"],
  // ---- teaching / school ----
  ["blackboard", "tábla", "noun", "teaching"], ["notebook", "füzet", "noun", "teaching"],
  ["ruler", "vonalzó", "noun", "teaching"], ["rubber", "radír", "noun", "teaching"],
  ["dictionary", "szótár", "noun", "teaching"], ["sentence", "mondat", "noun", "teaching"],
  ["spelling", "helyesírás", "noun", "teaching"], ["mistake", "hiba", "noun", "teaching"],
  ["example", "példa", "noun", "teaching"], ["translate", "lefordítani", "verb", "teaching"],
  // ---- family / events ----
  ["grandson", "unoka (fiú)", "noun", "family"], ["granddaughter", "unoka (lány)", "noun", "family"],
  ["relative", "rokon", "noun", "family"], ["neighbour", "szomszéd", "noun", "family"],
  ["guest", "vendég", "noun", "family"], ["wedding", "esküvő", "noun", "family"],
  ["anniversary", "évforduló", "noun", "family"], ["celebration", "ünneplés", "noun", "family"],
  ["surprise", "meglepetés", "noun", "family"], ["candle", "gyertya", "noun", "family"],
  ["balloon", "lufi", "noun", "family"], ["toast (drink)", "pohárköszöntő", "phrase", "family"],
  // ---- feelings / conversation ----
  ["proud", "büszke", "adjective", "feelings"], ["lonely", "magányos", "adjective", "feelings"],
  ["comfortable", "kényelmes", "adjective", "feelings"], ["confident", "magabiztos", "adjective", "feelings"],
  ["disappointed", "csalódott", "adjective", "feelings"], ["grateful", "hálás", "adjective", "feelings"],
  ["by the way", "erről jut eszembe", "phrase", "conversation"], ["at the moment", "jelenleg", "phrase", "conversation"],
  ["for example", "például", "phrase", "conversation"], ["in fact", "valójában", "phrase", "conversation"],
  ["I agree", "egyetértek", "phrase", "conversation"], ["that's right", "így van", "phrase", "conversation"],
  ["no problem", "semmi gond", "phrase", "conversation"], ["never mind", "nem baj", "phrase", "conversation"],
  // ---- travel / experiences ----
  ["sightseeing", "városnézés", "noun", "travel"], ["souvenir", "ajándéktárgy", "noun", "travel"],
  ["postcard", "képeslap", "noun", "travel"], ["backpack", "hátizsák", "noun", "travel"],
  ["currency", "valuta", "noun", "travel"], ["exchange", "pénzváltás", "noun", "travel"],
  ["border", "határ", "noun", "travel"], ["abroad", "külföldön", "adverb", "travel"],
  ["local", "helyi", "adjective", "travel"], ["distance", "távolság", "noun", "travel"],
  // ---- time ----
  ["midday", "dél (időpont)", "noun", "time"], ["midnight", "éjfél", "noun", "time"],
  ["fortnight", "két hét", "noun", "time"], ["century", "évszázad", "noun", "time"],
  ["moment", "pillanat", "noun", "time"], ["recently", "nemrég", "adverb", "time"],
  ["already", "már", "adverb", "time"], ["yet", "még", "adverb", "time"],
  // ---- batch 2b: reach the target ----
  ["arrivals board", "érkezési tábla", "phrase", "airport"], ["departures board", "indulási tábla", "phrase", "airport"],
  ["hand baggage", "kézipoggyász", "phrase", "airport"], ["check-in desk", "check-in pult", "phrase", "airport"],
  ["passport control", "útlevél-ellenőrzés", "phrase", "airport"], ["security check", "biztonsági ellenőrzés", "phrase", "airport"],
  ["boarding pass", "beszállókártya", "phrase", "airport"], ["flight attendant", "légiutas-kísérő", "phrase", "flying"],
  ["seat number", "ülésszám", "phrase", "flying"], ["exit", "kijárat", "noun", "airport"],
  ["information desk", "információs pult", "phrase", "airport"], ["waiting area", "váróterem", "phrase", "airport"],
  ["half board", "félpanzió", "phrase", "hotel"], ["full board", "teljes panzió", "phrase", "hotel"],
  ["ground floor", "földszint", "phrase", "hotel"], ["top floor", "legfelső emelet", "phrase", "hotel"],
  ["swimming pool", "úszómedence", "phrase", "hotel"], ["car park", "parkoló", "phrase", "hotel"],
  ["bill (hotel)", "számla (hotel)", "phrase", "hotel"], ["extra bed", "pótágy", "phrase", "hotel"],
  ["menu of the day", "napi menü", "phrase", "services"], ["vegetarian", "vegetáriánus", "adjective", "services"],
  ["well done (meat)", "jól átsütve", "phrase", "services"], ["bottle of water", "üveg víz", "phrase", "services"],
  ["receipt", "nyugta", "noun", "services"], ["queue", "sor (várakozó)", "noun", "services"],
  ["one way", "egyirányú", "phrase", "transport"], ["return journey", "visszaút", "phrase", "transport"],
  ["rush hour", "csúcsforgalom", "phrase", "transport"], ["next stop", "következő megálló", "phrase", "transport"],
  ["speed", "sebesség", "noun", "transport"], ["driver's seat", "vezetőülés", "phrase", "transport"],
  ["main square", "főtér", "phrase", "town"], ["old town", "óváros", "phrase", "town"],
  ["city centre", "városközpont", "phrase", "town"], ["pedestrian", "gyalogos", "noun", "town"],
  ["bakery", "pékség", "noun", "town"], ["butcher", "hentes", "noun", "town"],
  ["greengrocer", "zöldséges", "noun", "town"], ["newsagent", "újságos", "noun", "town"],
  ["frozen food", "fagyasztott étel", "phrase", "shopping"], ["shopping list", "bevásárlólista", "phrase", "shopping"],
  ["reduced", "leárazva", "adjective", "shopping"], ["sold out", "elfogyott", "phrase", "shopping"],
  ["dining table", "étkezőasztal", "phrase", "home"], ["armchair", "fotel", "noun", "home"],
  ["bookshelf", "könyvespolc", "noun", "home"], ["front door", "bejárati ajtó", "phrase", "home"],
  ["back garden", "hátsó kert", "phrase", "home"], ["central heating", "központi fűtés", "phrase", "home"],
  ["waiting room", "váróterem", "phrase", "health"], ["health centre", "egészségügyi központ", "phrase", "health"],
  ["blood pressure", "vérnyomás", "phrase", "health"], ["check-up", "kivizsgálás", "noun", "health"],
  ["family doctor", "háziorvos", "phrase", "health"], ["first aid", "elsősegély", "phrase", "health"],
  ["grandchildren", "unokák", "noun", "family"], ["in-laws", "após-anyós", "phrase", "family"],
  ["get-together", "összejövetel", "noun", "family"], ["family reunion", "családi találkozó", "phrase", "family"],
];
